var h;h||=typeof Module != 'undefined' ? Module : {};h.expectedDataFileDownloads||(h.expectedDataFileDownloads=0);h.expectedDataFileDownloads++;
(()=>{var a="undefined"!=typeof ENVIRONMENT_IS_WASM_WORKER&&ENVIRONMENT_IS_WASM_WORKER;"undefined"!=typeof ENVIRONMENT_IS_PTHREAD&&ENVIRONMENT_IS_PTHREAD||a||function(b){function c(p,t,v){var r=new XMLHttpRequest;r.open("GET",p,!0);r.responseType="arraybuffer";r.onprogress=A=>{var D=t;A.total&&(D=A.total);if(A.loaded){r.o?h.dataFileDownloads[p].loaded=A.loaded:(r.o=!0,h.dataFileDownloads||(h.dataFileDownloads={}),h.dataFileDownloads[p]={loaded:A.loaded,total:D});var H=D=A=0,T;for(T in h.dataFileDownloads){var va=
h.dataFileDownloads[T];A+=va.total;D+=va.loaded;H++}A=Math.ceil(A*h.expectedDataFileDownloads/H);h.setStatus?.(`Downloading data... (${D}/${A})`)}else h.dataFileDownloads||h.setStatus?.("Downloading data...")};r.onerror=()=>{throw Error("NetworkError for: "+p);};r.onload=()=>{if(200==r.status||304==r.status||206==r.status||0==r.status&&r.response)v(r.response);else throw Error(r.statusText+" : "+r.responseURL);};r.send(null)}function d(p){console.error("package error:",p)}function e(p){function t(D,
H,T){this.start=D;this.end=H;this.audio=T}function v(D){if(!D)throw"Loading data file failed."+Error().stack;if(D.constructor.name!==ArrayBuffer.name)throw"bad input to processPackageData"+Error().stack;D=new Uint8Array(D);t.prototype.oa=D;D=b.files;for(var H=0;H<D.length;++H)t.prototype.o[D[H].filename].onload();p.removeRunDependency("datafile_index.data")}p.FS_createPath("/","data",!0,!0);p.FS_createPath("/data","atlas",!0,!0);p.FS_createPath("/data","config",!0,!0);p.FS_createPath("/data","misc",
!0,!0);p.FS_createPath("/data","stages",!0,!0);p.FS_createPath("/data","widgets",!0,!0);p.FS_createPath("/","fonts",!0,!0);p.FS_createPath("/","gfx",!0,!0);p.FS_createPath("/gfx","atlas",!0,!0);p.FS_createPath("/","music",!0,!0);p.FS_createPath("/","sound",!0,!0);t.prototype={o:{},open:function(D,H){this.name=H;this.o[H]=this;p.addRunDependency(`fp ${this.name}`)},onload:function(){this.finish(this.oa.subarray(this.start,this.end))},finish:function(D){p.FS_createDataFile(this.name,null,D,!0,!0,!0);
p.removeRunDependency(`fp ${this.name}`);this.o[this.name]=null}};for(var r=b.files,A=0;A<r.length;++A)(new t(r[A].start,r[A].end,r[A].audio||0)).open("GET",r[A].filename);p.addRunDependency("datafile_index.data");p.preloadResults||(p.preloadResults={});p.preloadResults["index.data"]={Kb:!1};n?(v(n),n=null):m=v}"object"===typeof window?window.encodeURIComponent(window.location.pathname.toString().substring(0,window.location.pathname.toString().lastIndexOf("/"))+"/"):"undefined"===typeof process&&
"undefined"!==typeof location&&encodeURIComponent(location.pathname.toString().substring(0,location.pathname.toString().lastIndexOf("/"))+"/");"function"!==typeof h.locateFilePackage||h.locateFile||(h.locateFile=h.locateFilePackage,aa("warning: you defined Module.locateFilePackage, that has been renamed to Module.locateFile (using your locateFilePackage for now)"));var f=h.locateFile?h.locateFile("index.data",""):"index.data",g=b.remote_package_size,m=null,n=h.getPreloadedPackage?h.getPreloadedPackage(f,
g):null;n||c(f,g,p=>{m?(m(p),m=null):n=p},d);h.calledRun?e(h):(h.preRun||(h.preRun=[]),h.preRun.push(e))}({files:[{filename:"/data/atlas/atlas.json",start:0,end:1118},{filename:"/data/config/config.json",start:1118,end:1461},{filename:"/data/misc/credits.txt",start:1461,end:3269},{filename:"/data/misc/story.txt",start:3269,end:3950},{filename:"/data/stages/000.json",start:3950,end:13039},{filename:"/data/stages/001.json",start:13039,end:22128},{filename:"/data/stages/002.json",start:22128,end:22312},
{filename:"/data/widgets/controls.json",start:22312,end:23062},{filename:"/data/widgets/options.json",start:23062,end:24354},{filename:"/data/widgets/stage.json",start:24354,end:24852},{filename:"/data/widgets/title.json",start:24852,end:25359},{filename:"/fonts/EnterCommand.ttf",start:25359,end:65415},{filename:"/gfx/atlas/README.txt",start:65415,end:65657},{filename:"/gfx/atlas/atlas.png",start:65657,end:74658},{filename:"/gfx/by-nc-sa.png",start:74658,end:97133},{filename:"/music/puzzle-1-b.mp3",
start:97133,end:1059069,audio:1},{filename:"/sound/135936__bradwesson__collectcoin.mp3",start:1059069,end:1070606,audio:1},{filename:"/sound/331381__qubodup__public-domain-jump-sound.mp3",start:1070606,end:1073549,audio:1},{filename:"/sound/449069__ricniclas__fanfare.mp3",start:1073549,end:1106402,audio:1},{filename:"/sound/clock.mp3",start:1106402,end:1108300,audio:1},{filename:"/sound/expired.mp3",start:1108300,end:1134649,audio:1},{filename:"/sound/fail.mp3",start:1134649,end:1152012,audio:1},
{filename:"/sound/item.mp3",start:1152012,end:1166031,audio:1},{filename:"/sound/negative.mp3",start:1166031,end:1168974,audio:1},{filename:"/sound/nudge.mp3",start:1168974,end:1171499,audio:1},{filename:"/sound/tip.mp3",start:1171499,end:1173815,audio:1},{filename:"/sound/ulrichmetzner__churchbell.mp3",start:1173815,end:1233996,audio:1},{filename:"/sound/wipe.mp3",start:1233996,end:1248433,audio:1}],remote_package_size:1248433})})();var ba=Object.assign({},h),ca=[],da="./this.program",ea="",fa;
"undefined"!=typeof document&&document.currentScript&&(ea=document.currentScript.src);ea=ea.startsWith("blob:")?"":ea.substr(0,ea.replace(/[?#].*/,"").lastIndexOf("/")+1);fa=a=>fetch(a,{credentials:"same-origin"}).then(b=>b.ok?b.arrayBuffer():Promise.reject(Error(b.status+" : "+b.url)));var ha=h.print||console.log.bind(console),aa=h.printErr||console.error.bind(console);Object.assign(h,ba);ba=null;h.arguments&&(ca=h.arguments);h.thisProgram&&(da=h.thisProgram);
var ia=h.wasmBinary,ja,ka=!1,la,k,l,ma,na,q,u,w,x,oa=[],pa=[],qa=[],ra=[];function sa(){var a=h.preRun.shift();oa.unshift(a)}var ta=0,ua=null,wa=null;function xa(){ta++;h.monitorRunDependencies?.(ta)}function ya(){ta--;h.monitorRunDependencies?.(ta);if(0==ta&&(null!==ua&&(clearInterval(ua),ua=null),wa)){var a=wa;wa=null;a()}}function za(a){h.onAbort?.(a);a="Aborted("+a+")";aa(a);ka=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}
var Aa=a=>a.startsWith("data:application/octet-stream;base64,"),Ba;function Ca(a){if(a==Ba&&ia)return new Uint8Array(ia);throw"both async and sync fetching of the wasm failed";}function Da(a){return ia?Promise.resolve().then(()=>Ca(a)):fa(a).then(b=>new Uint8Array(b),()=>Ca(a))}function Ea(a,b,c){return Da(a).then(d=>WebAssembly.instantiate(d,b)).then(c,d=>{aa(`failed to asynchronously prepare wasm: ${d}`);za(d)})}
function Fa(a,b){var c=Ba;ia||"function"!=typeof WebAssembly.instantiateStreaming||Aa(c)||"function"!=typeof fetch?Ea(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){aa(`wasm streaming compile failed: ${e}`);aa("falling back to ArrayBuffer instantiation");return Ea(c,a,b)}))}
var y,z,Ma={510796:a=>{a=(a?B(l,a):"")+"\n\nAbort/Retry/Ignore/AlwaysIgnore? [ariA] :";a=window.prompt(a,"i");null===a&&(a="i");return Ga(Ha(a),"i8",Ia)},511021:()=>"undefined"!==typeof AudioContext||"undefined"!==typeof webkitAudioContext?!0:!1,511168:()=>"undefined"!==typeof navigator.mediaDevices&&"undefined"!==typeof navigator.mediaDevices.getUserMedia||"undefined"!==typeof navigator.webkitGetUserMedia?!0:!1,511402:a=>{"undefined"===typeof h.SDL2&&(h.SDL2={});var b=h.SDL2;a?b.capture={}:b.audio=
{};b.m||("undefined"!==typeof AudioContext?b.m=new AudioContext:"undefined"!==typeof webkitAudioContext&&(b.m=new webkitAudioContext),b.m&&Ja(b.m));return void 0===b.m?-1:0},511895:()=>h.SDL2.m.sampleRate,511963:(a,b,c,d)=>{function e(){}function f(m){void 0!==g.capture.Z&&(clearTimeout(g.capture.Z),g.capture.Z=void 0);g.capture.ga=g.m.createMediaStreamSource(m);g.capture.A=g.m.createScriptProcessor(b,a,1);g.capture.A.onaudioprocess=function(n){void 0!==g&&void 0!==g.capture&&(n.outputBuffer.getChannelData(0).fill(0),
g.capture.na=n.inputBuffer,Ka(c,[d]))};g.capture.ga.connect(g.capture.A);g.capture.A.connect(g.m.destination);g.capture.stream=m}var g=h.SDL2;g.capture.ja=g.m.createBuffer(a,b,g.m.sampleRate);g.capture.ja.getChannelData(0).fill(0);g.capture.Z=setTimeout(function(){g.capture.na=g.capture.ja;Ka(c,[d])},b/g.m.sampleRate*1E3);void 0!==navigator.mediaDevices&&void 0!==navigator.mediaDevices.getUserMedia?navigator.mediaDevices.getUserMedia({audio:!0,video:!1}).then(f).catch(e):void 0!==navigator.webkitGetUserMedia&&
navigator.webkitGetUserMedia({audio:!0,video:!1},f,e)},513615:(a,b,c,d)=>{var e=h.SDL2;e.audio.A=e.m.createScriptProcessor(b,0,a);e.audio.A.onaudioprocess=function(f){void 0!==e&&void 0!==e.audio&&(e.audio.za=f.outputBuffer,Ka(c,[d]))};e.audio.A.connect(e.m.destination)},514025:(a,b)=>{for(var c=h.SDL2,d=c.capture.na.numberOfChannels,e=0;e<d;++e){var f=c.capture.na.getChannelData(e);if(f.length!=b)throw"Web Audio capture buffer length mismatch! Destination size: "+f.length+" samples vs expected "+
b+" samples!";if(1==d)for(var g=0;g<b;++g)La(a+4*g,f[g]);else for(g=0;g<b;++g)La(a+4*(g*d+e),f[g])}},514630:(a,b)=>{for(var c=h.SDL2,d=c.audio.za.numberOfChannels,e=0;e<d;++e){var f=c.audio.za.getChannelData(e);if(f.length!=b)throw"Web Audio output buffer length mismatch! Destination size: "+f.length+" samples vs expected "+b+" samples!";for(var g=0;g<b;++g)f[g]=w[a+(g*d+e<<2)>>2]}},515110:a=>{var b=h.SDL2;if(a){void 0!==b.capture.Z&&clearTimeout(b.capture.Z);if(void 0!==b.capture.stream){a=b.capture.stream.getAudioTracks();
for(var c=0;c<a.length;c++)b.capture.stream.removeTrack(a[c]);b.capture.stream=void 0}void 0!==b.capture.A&&(b.capture.A.onaudioprocess=function(){},b.capture.A.disconnect(),b.capture.A=void 0);void 0!==b.capture.ga&&(b.capture.ga.disconnect(),b.capture.ga=void 0);void 0!==b.capture.ja&&(b.capture.ja=void 0);b.capture=void 0}else void 0!=b.audio.A&&(b.audio.A.disconnect(),b.audio.A=void 0),b.audio=void 0;void 0!==b.m&&void 0===b.audio&&void 0===b.capture&&(b.m.close(),b.m=void 0)},516282:()=>window.innerWidth,
516312:()=>window.innerHeight,516343:(a,b,c)=>{h.SDL2||(h.SDL2={});var d=h.SDL2;d.Va!==h.canvas&&(d.G=h.createContext(h.canvas,!1,!0),d.Va=h.canvas);if(d.w!==a||d.hb!==b||d.jb!==d.G)d.image=d.G.createImageData(a,b),d.w=a,d.hb=b,d.jb=d.G;a=d.image.data;b=c>>2;var e=0;if("undefined"!==typeof CanvasPixelArray&&a instanceof CanvasPixelArray)for(c=a.length;e<c;){var f=q[b];a[e]=f&255;a[e+1]=f>>8&255;a[e+2]=f>>16&255;a[e+3]=255;b++;e+=4}else if(d.Ya!==a&&(d.Xa=new Int32Array(a.buffer),d.Za=new Uint8Array(a.buffer),
d.Ya=a),a=d.Xa,c=a.length,a.set(q.subarray(b,b+c)),a=d.Za,b=3,e=b+4*c,0==c%8)for(;b<e;)a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0;else for(;b<e;)a[b]=255,b=b+4|0;d.G.putImageData(d.image,0,0)},517812:(a,b,c,d,e)=>{var f=document.createElement("canvas");f.width=a;f.height=b;var g=f.getContext("2d");a=g.createImageData(a,b);b=a.data;e>>=2;var m=0,n;if("undefined"!==typeof CanvasPixelArray&&b instanceof CanvasPixelArray)for(n=
b.length;m<n;){var p=q[e];b[m]=p&255;b[m+1]=p>>8&255;b[m+2]=p>>16&255;b[m+3]=p>>24&255;e++;m+=4}else b=new Int32Array(b.buffer),n=b.length,b.set(q.subarray(e,e+n));g.putImageData(a,0,0);c=0===c&&0===d?"url("+f.toDataURL()+"), auto":"url("+f.toDataURL()+") "+c+" "+d+", auto";d=C(c.length+1);E(c,l,d,c.length+1);return d},518801:a=>{h.canvas&&(h.canvas.style.cursor=a?B(l,a):"")},518884:()=>{h.canvas&&(h.canvas.style.cursor="none")}};
function Na(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}var Oa=a=>{for(;0<a.length;)a.shift()(h)},Pa=h.noExitRuntime||!0;
function La(a,b){var c="float";c.endsWith("*")&&(c="*");switch(c){case "i1":k[a]=b;break;case "i8":k[a]=b;break;case "i16":ma[a>>1]=b;break;case "i32":q[a>>2]=b;break;case "i64":za("to do setValue(i64) use WASM_BIGINT");case "float":w[a>>2]=b;break;case "double":x[a>>3]=b;break;case "*":u[a>>2]=b;break;default:za(`invalid type for setValue: ${c}`)}}
var Qa=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},Ra=a=>{var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=Qa(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},Sa=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&=b.substr(0,b.length-1);return a+b},Ta=a=>{if("/"===
a)return"/";a=Ra(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)},Ua=()=>{if("object"==typeof crypto&&"function"==typeof crypto.getRandomValues)return a=>crypto.getRandomValues(a);za("initRandomDevice")},Va=a=>(Va=Ua())(a),Wa=(...a)=>{for(var b="",c=!1,d=a.length-1;-1<=d&&!c;d--){c=0<=d?a[d]:"/";if("string"!=typeof c)throw new TypeError("Arguments to path.resolve must be strings");if(!c)return"";b=c+"/"+b;c="/"===c.charAt(0)}b=Qa(b.split("/").filter(e=>!!e),!c).join("/");
return(c?"/":"")+b||"."},Xa="undefined"!=typeof TextDecoder?new TextDecoder:void 0,B=(a,b,c)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&Xa)return Xa.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var g=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|g:(e&7)<<18|f<<12|g<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},
Ya=[],Za=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},E=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var m=a.charCodeAt(++f);g=65536+((g&1023)<<10)|m&1023}if(127>=g){if(c>=d)break;b[c++]=g}else{if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6}else{if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&
63}b[c++]=128|g>>6&63}b[c++]=128|g&63}}b[c]=0;return c-e};function Ha(a,b){var c=Array(Za(a)+1);a=E(a,c,0,c.length);b&&(c.length=a);return c}var $a=[];function ab(a,b){$a[a]={input:[],v:[],L:b};bb(a,cb)}
var cb={open(a){var b=$a[a.node.X];if(!b)throw new F(43);a.j=b;a.seekable=!1},close(a){a.j.L.ca(a.j)},ca(a){a.j.L.ca(a.j)},read(a,b,c,d){if(!a.j||!a.j.L.Ca)throw new F(60);for(var e=0,f=0;f<d;f++){try{var g=a.j.L.Ca(a.j)}catch(m){throw new F(29);}if(void 0===g&&0===e)throw new F(6);if(null===g||void 0===g)break;e++;b[c+f]=g}e&&(a.node.timestamp=Date.now());return e},write(a,b,c,d){if(!a.j||!a.j.L.qa)throw new F(60);try{for(var e=0;e<d;e++)a.j.L.qa(a.j,b[c+e])}catch(f){throw new F(29);}d&&(a.node.timestamp=
Date.now());return e}},db={Ca(){a:{if(!Ya.length){var a=null;"undefined"!=typeof window&&"function"==typeof window.prompt&&(a=window.prompt("Input: "),null!==a&&(a+="\n"));if(!a){a=null;break a}Ya=Ha(a,!0)}a=Ya.shift()}return a},qa(a,b){null===b||10===b?(ha(B(a.v,0)),a.v=[]):0!=b&&a.v.push(b)},ca(a){a.v&&0<a.v.length&&(ha(B(a.v,0)),a.v=[])},mb(){return{Db:25856,Fb:5,Cb:191,Eb:35387,Bb:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},nb(){return 0},ob(){return[24,80]}},
eb={qa(a,b){null===b||10===b?(aa(B(a.v,0)),a.v=[]):0!=b&&a.v.push(b)},ca(a){a.v&&0<a.v.length&&(aa(B(a.v,0)),a.v=[])}},gb=a=>{a=65536*Math.ceil(a/65536);var b=fb(65536,a);b?(l.fill(0,b,b+a),a=b):a=0;return a};function hb(a,b){var c=a.g?a.g.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.g,a.g=new Uint8Array(b),0<a.l&&a.g.set(c.subarray(0,a.l),0))}
var G={I:null,K(){return G.createNode(null,"/",16895,0)},createNode(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new F(63);G.I||(G.I={dir:{node:{H:G.h.H,B:G.h.B,V:G.h.V,ha:G.h.ha,Ma:G.h.Ma,la:G.h.la,Na:G.h.Na,ia:G.h.ia,ka:G.h.ka},stream:{R:G.i.R}},file:{node:{H:G.h.H,B:G.h.B},stream:{R:G.i.R,read:G.i.read,write:G.i.write,va:G.i.va,pa:G.i.pa,Ja:G.i.Ja}},link:{node:{H:G.h.H,B:G.h.B,Y:G.h.Y},stream:{}},ya:{node:{H:G.h.H,B:G.h.B},stream:ib}});c=jb(a,b,c,d);I(c.mode)?(c.h=G.I.dir.node,c.i=G.I.dir.stream,
c.g={}):32768===(c.mode&61440)?(c.h=G.I.file.node,c.i=G.I.file.stream,c.l=0,c.g=null):40960===(c.mode&61440)?(c.h=G.I.link.node,c.i=G.I.link.stream):8192===(c.mode&61440)&&(c.h=G.I.ya.node,c.i=G.I.ya.stream);c.timestamp=Date.now();a&&(a.g[b]=c,a.timestamp=c.timestamp);return c},Mb(a){return a.g?a.g.subarray?a.g.subarray(0,a.l):new Uint8Array(a.g):new Uint8Array(0)},h:{H(a){var b={};b.ab=8192===(a.mode&61440)?a.id:1;b.Da=a.id;b.mode=a.mode;b.tb=1;b.uid=0;b.gb=0;b.X=a.X;I(a.mode)?b.size=4096:32768===
(a.mode&61440)?b.size=a.l:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.Ra=new Date(a.timestamp);b.sb=new Date(a.timestamp);b.Ua=new Date(a.timestamp);b.Sa=4096;b.Ta=Math.ceil(b.size/b.Sa);return b},B(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);if(void 0!==b.size&&(b=b.size,a.l!=b))if(0==b)a.g=null,a.l=0;else{var c=a.g;a.g=new Uint8Array(b);c&&a.g.set(c.subarray(0,Math.min(b,a.l)));a.l=b}},V(){throw kb[44];},ha(a,b,c,d){return G.createNode(a,b,c,
d)},Ma(a,b,c){if(I(a.mode)){try{var d=lb(b,c)}catch(f){}if(d)for(var e in d.g)throw new F(55);}delete a.parent.g[a.name];a.parent.timestamp=Date.now();a.name=c;b.g[c]=a;b.timestamp=a.parent.timestamp},la(a,b){delete a.g[b];a.timestamp=Date.now()},Na(a,b){var c=lb(a,b),d;for(d in c.g)throw new F(55);delete a.g[b];a.timestamp=Date.now()},ia(a){var b=[".",".."],c;for(c of Object.keys(a.g))b.push(c);return b},ka(a,b,c){a=G.createNode(a,b,41471,0);a.link=c;return a},Y(a){if(40960!==(a.mode&61440))throw new F(28);
return a.link}},i:{read(a,b,c,d,e){var f=a.node.g;if(e>=a.node.l)return 0;a=Math.min(a.node.l-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write(a,b,c,d,e,f){if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.g||a.g.subarray)){if(f)return a.g=b.subarray(c,c+d),a.l=d;if(0===a.l&&0===e)return a.g=b.slice(c,c+d),a.l=d;if(e+d<=a.l)return a.g.set(b.subarray(c,c+d),e),d}hb(a,e+d);if(a.g.subarray&&b.subarray)a.g.set(b.subarray(c,c+d),e);else for(f=
0;f<d;f++)a.g[e+f]=b[c+f];a.l=Math.max(a.l,e+d);return d},R(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.l);if(0>b)throw new F(28);return b},va(a,b,c){hb(a.node,b+c);a.node.l=Math.max(a.node.l,b+c)},pa(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new F(43);a=a.node.g;if(e&2||!a||a.buffer!==k.buffer){d=!0;e=gb(b);if(!e)throw new F(48);if(a){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);k.set(a,e)}}else d=!1,e=a.byteOffset;
return{vb:e,Qa:d}},Ja(a,b,c,d){G.i.write(a,b,0,d,c,!1);return 0}}},mb=(a,b,c)=>{var d=`al ${a}`;fa(a).then(e=>{b(new Uint8Array(e));d&&ya(d)},()=>{if(c)c();else throw`Loading data file "${a}" failed.`;});d&&xa(d)},nb=h.preloadPlugins||[],qb=(a,b,c,d)=>{"undefined"!=typeof ob&&pb();var e=!1;nb.forEach(f=>{!e&&f.canHandle(b)&&(f.handle(a,b,c,d),e=!0)});return e},sb=(a,b,c,d,e,f,g,m,n,p)=>{function t(A){function D(H){p?.();m||rb(a,b,H,d,e,n);f?.();ya(r)}qb(A,v,D,()=>{g?.();ya(r)})||D(A)}var v=b?Wa(Ra(a+
"/"+b)):a,r=`cp ${v}`;xa(r);"string"==typeof c?mb(c,t,g):t(c)},tb=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},ub=null,vb={},wb=[],xb=1,yb=null,zb=!1,Ab=!0,F=class{constructor(a){this.name="ErrnoError";this.s=a}},kb={},Bb=class{constructor(){this.o={};this.node=null}get flags(){return this.o.flags}set flags(a){this.o.flags=a}get position(){return this.o.position}set position(a){this.o.position=a}},Cb=class{constructor(a,b,c,d){a||=this;this.parent=a;this.K=a.K;this.W=null;this.id=xb++;this.name=
b;this.mode=c;this.h={};this.i={};this.X=d}get read(){return 365===(this.mode&365)}set read(a){a?this.mode|=365:this.mode&=-366}get write(){return 146===(this.mode&146)}set write(a){a?this.mode|=146:this.mode&=-147}get pb(){return I(this.mode)}get Fa(){return 8192===(this.mode&61440)}};
function Db(a,b={}){a=Wa(a);if(!a)return{path:"",node:null};b=Object.assign({Ba:!0,ra:0},b);if(8<b.ra)throw new F(32);a=a.split("/").filter(g=>!!g);for(var c=ub,d="/",e=0;e<a.length;e++){var f=e===a.length-1;if(f&&b.parent)break;c=lb(c,a[e]);d=Ra(d+"/"+a[e]);c.W&&(!f||f&&b.Ba)&&(c=c.W.root);if(!f||b.U)for(f=0;40960===(c.mode&61440);)if(c=Eb(d),d=Wa(Sa(d),c),c=Db(d,{ra:b.ra+1}).node,40<f++)throw new F(32);}return{path:d,node:c}}
function Fb(a){for(var b;;){if(a===a.parent)return a=a.K.Ia,b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}}function Gb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%yb.length}function lb(a,b){var c=I(a.mode)?(c=Hb(a,"x"))?c:a.h.V?0:2:54;if(c)throw new F(c);for(c=yb[Gb(a.id,b)];c;c=c.S){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.h.V(a,b)}
function jb(a,b,c,d){a=new Cb(a,b,c,d);b=Gb(a.parent.id,a.name);a.S=yb[b];return yb[b]=a}function I(a){return 16384===(a&61440)}function Jb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function Hb(a,b){if(Ab)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function Kb(a,b){try{return lb(a,b),20}catch(c){}return Hb(a,"wx")}function Lb(a){a=wb[a];if(!a)throw new F(8);return a}
function Mb(a,b=-1){a=Object.assign(new Bb,a);if(-1==b)a:{for(b=0;4096>=b;b++)if(!wb[b])break a;throw new F(33);}a.N=b;return wb[b]=a}function Nb(a,b=-1){a=Mb(a,b);a.i?.Ib?.(a);return a}var ib={open(a){a.i=vb[a.node.X].i;a.i.open?.(a)},R(){throw new F(70);}};function bb(a,b){vb[a]={i:b}}
function Ob(a,b){var c="/"===b;if(c&&ub)throw new F(10);if(!c&&b){var d=Db(b,{Ba:!1});b=d.path;d=d.node;if(d.W)throw new F(10);if(!I(d.mode))throw new F(54);}b={type:a,Qb:{},Ia:b,rb:[]};a=a.K(b);a.K=b;b.root=a;c?ub=a:d&&(d.W=b,d.K&&d.K.rb.push(b))}function Pb(a,b,c){var d=Db(a,{parent:!0}).node;a=Ta(a);if(!a||"."===a||".."===a)throw new F(28);var e=Kb(d,a);if(e)throw new F(e);if(!d.h.ha)throw new F(63);return d.h.ha(d,a,b,c)}function Qb(a){return Pb(a,16895,0)}
function Rb(a,b,c){"undefined"==typeof c&&(c=b,b=438);return Pb(a,b|8192,c)}function Sb(a,b){if(!Wa(a))throw new F(44);var c=Db(b,{parent:!0}).node;if(!c)throw new F(44);b=Ta(b);var d=Kb(c,b);if(d)throw new F(d);if(!c.h.ka)throw new F(63);c.h.ka(c,b,a)}
function Tb(a){var b=Db(a,{parent:!0}).node;if(!b)throw new F(44);var c=Ta(a);a=lb(b,c);a:{try{var d=lb(b,c)}catch(f){d=f.s;break a}var e=Hb(b,"wx");d=e?e:I(d.mode)?31:0}if(d)throw new F(d);if(!b.h.la)throw new F(63);if(a.W)throw new F(10);b.h.la(b,c);b=Gb(a.parent.id,a.name);if(yb[b]===a)yb[b]=a.S;else for(b=yb[b];b;){if(b.S===a){b.S=a.S;break}b=b.S}}function Eb(a){a=Db(a).node;if(!a)throw new F(44);if(!a.h.Y)throw new F(28);return Wa(Fb(a.parent),a.h.Y(a))}
function Ub(a,b){a=Db(a,{U:!b}).node;if(!a)throw new F(44);if(!a.h.H)throw new F(63);return a.h.H(a)}function Vb(a){return Ub(a,!0)}function Wb(a,b){a="string"==typeof a?Db(a,{U:!0}).node:a;if(!a.h.B)throw new F(63);a.h.B(a,{mode:b&4095|a.mode&-4096,timestamp:Date.now()})}
function Xb(a,b,c){if(""===a)throw new F(44);if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?("undefined"==typeof c?438:c)&4095|32768:0;if("object"==typeof a)var e=a;else{a=Ra(a);try{e=Db(a,{U:!(b&131072)}).node}catch(f){}}d=!1;if(b&64)if(e){if(b&128)throw new F(20);}else e=Pb(a,c,0),d=!0;if(!e)throw new F(44);8192===(e.mode&61440)&&(b&=-513);if(b&65536&&!I(e.mode))throw new F(54);if(!d&&(c=
e?40960===(e.mode&61440)?32:I(e.mode)&&("r"!==Jb(b)||b&512)?31:Hb(e,Jb(b)):44))throw new F(c);if(b&512&&!d){c=e;c="string"==typeof c?Db(c,{U:!0}).node:c;if(!c.h.B)throw new F(63);if(I(c.mode))throw new F(31);if(32768!==(c.mode&61440))throw new F(28);if(d=Hb(c,"w"))throw new F(d);c.h.B(c,{size:0,timestamp:Date.now()})}b&=-131713;e=Mb({node:e,path:Fb(e),flags:b,seekable:!0,position:0,i:e.i,xb:[],error:!1});e.i.open&&e.i.open(e);!h.logReadFiles||b&1||(Yb||={},a in Yb||(Yb[a]=1));return e}
function Zb(a){if(null===a.N)throw new F(8);a.P&&(a.P=null);try{a.i.close&&a.i.close(a)}catch(b){throw b;}finally{wb[a.N]=null}a.N=null}function $b(a,b,c){if(null===a.N)throw new F(8);if(!a.seekable||!a.i.R)throw new F(70);if(0!=c&&1!=c&&2!=c)throw new F(28);a.position=a.i.R(a,b,c);a.xb=[];return a.position}
function ac(a,b,c,d,e,f){if(0>d||0>e)throw new F(28);if(null===a.N)throw new F(8);if(0===(a.flags&2097155))throw new F(8);if(I(a.node.mode))throw new F(31);if(!a.i.write)throw new F(28);a.seekable&&a.flags&1024&&$b(a,0,2);var g="undefined"!=typeof e;if(!g)e=a.position;else if(!a.seekable)throw new F(70);b=a.i.write(a,b,c,d,e,f);g||(a.position+=b);return b}
function bc(a,b){a="string"==typeof a?a:Fb(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=Ra(a+"/"+c);try{Qb(d)}catch(e){}a=d}}return d}function cc(a,b,c,d){a=Ra(("string"==typeof a?a:Fb(a))+"/"+b);c=tb(c,d);return Pb(a,(void 0!==c?c:438)&4095|32768,0)}
function rb(a,b,c,d,e,f){var g=b;a&&(a="string"==typeof a?a:Fb(a),g=b?Ra(a+"/"+b):a);a=tb(d,e);g=Pb(g,(void 0!==a?a:438)&4095|32768,0);if(c){if("string"==typeof c){b=Array(c.length);d=0;for(e=c.length;d<e;++d)b[d]=c.charCodeAt(d);c=b}Wb(g,a|146);b=Xb(g,577);ac(b,c,0,c.length,0,f);Zb(b);Wb(g,a)}}
function dc(a,b,c,d){a=Ra(("string"==typeof a?a:Fb(a))+"/"+b);b=tb(!!c,!!d);dc.Ga||(dc.Ga=64);var e=dc.Ga++<<8|0;bb(e,{open(f){f.seekable=!1},close(){d?.buffer?.length&&d(10)},read(f,g,m,n){for(var p=0,t=0;t<n;t++){try{var v=c()}catch(r){throw new F(29);}if(void 0===v&&0===p)throw new F(6);if(null===v||void 0===v)break;p++;g[m+t]=v}p&&(f.node.timestamp=Date.now());return p},write(f,g,m,n){for(var p=0;p<n;p++)try{d(g[m+p])}catch(t){throw new F(29);}n&&(f.node.timestamp=Date.now());return p}});return Rb(a,
b,e)}function ec(a){if(!(a.Fa||a.pb||a.link||a.g)){if("undefined"!=typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");try{a.g=(void 0)(a.url),a.l=a.g.length}catch(b){throw new F(29);}}}
function fc(a,b,c,d,e){function f(n,p,t,v,r){n=n.node.g;if(r>=n.length)return 0;v=Math.min(n.length-r,v);if(n.slice)for(var A=0;A<v;A++)p[t+A]=n[r+A];else for(A=0;A<v;A++)p[t+A]=n.get(r+A);return v}if("undefined"!=typeof XMLHttpRequest)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";c={Fa:!1,url:c};var g=cc(a,b,d,e);c.g?g.g=c.g:c.url&&(g.g=null,g.url=c.url);Object.defineProperties(g,{l:{get:function(){return this.g.length}}});
var m={};Object.keys(g.i).forEach(n=>{var p=g.i[n];m[n]=(...t)=>{ec(g);return p(...t)}});m.read=(n,p,t,v,r)=>{ec(g);return f(n,p,t,v,r)};m.pa=(n,p,t)=>{ec(g);var v=gb(p);if(!v)throw new F(48);f(n,k,v,p,t);return{vb:v,Qa:!0}};g.i=m;return g}var J={},Yb;function gc(a,b,c){if("/"===b.charAt(0))return b;a=-100===a?"/":Lb(a).path;if(0==b.length){if(!c)throw new F(44);return a}return Ra(a+"/"+b)}
function hc(a,b,c){a=a(b);q[c>>2]=a.ab;q[c+4>>2]=a.mode;u[c+8>>2]=a.tb;q[c+12>>2]=a.uid;q[c+16>>2]=a.gb;q[c+20>>2]=a.X;z=[a.size>>>0,(y=a.size,1<=+Math.abs(y)?0<y?+Math.floor(y/4294967296)>>>0:~~+Math.ceil((y-+(~~y>>>0))/4294967296)>>>0:0)];q[c+24>>2]=z[0];q[c+28>>2]=z[1];q[c+32>>2]=4096;q[c+36>>2]=a.Ta;b=a.Ra.getTime();var d=a.sb.getTime(),e=a.Ua.getTime();z=[Math.floor(b/1E3)>>>0,(y=Math.floor(b/1E3),1<=+Math.abs(y)?0<y?+Math.floor(y/4294967296)>>>0:~~+Math.ceil((y-+(~~y>>>0))/4294967296)>>>0:0)];
q[c+40>>2]=z[0];q[c+44>>2]=z[1];u[c+48>>2]=b%1E3*1E6;z=[Math.floor(d/1E3)>>>0,(y=Math.floor(d/1E3),1<=+Math.abs(y)?0<y?+Math.floor(y/4294967296)>>>0:~~+Math.ceil((y-+(~~y>>>0))/4294967296)>>>0:0)];q[c+56>>2]=z[0];q[c+60>>2]=z[1];u[c+64>>2]=d%1E3*1E6;z=[Math.floor(e/1E3)>>>0,(y=Math.floor(e/1E3),1<=+Math.abs(y)?0<y?+Math.floor(y/4294967296)>>>0:~~+Math.ceil((y-+(~~y>>>0))/4294967296)>>>0:0)];q[c+72>>2]=z[0];q[c+76>>2]=z[1];u[c+80>>2]=e%1E3*1E6;z=[a.Da>>>0,(y=a.Da,1<=+Math.abs(y)?0<y?+Math.floor(y/
4294967296)>>>0:~~+Math.ceil((y-+(~~y>>>0))/4294967296)>>>0:0)];q[c+88>>2]=z[0];q[c+92>>2]=z[1];return 0}var ic=void 0;function jc(){var a=q[+ic>>2];ic+=4;return a}var kc={},lc=a=>{if(!(a instanceof Na||"unwind"==a))throw a;},mc=0,nc=a=>{la=a;Pa||0<mc||(h.onExit?.(a),ka=!0);throw new Na(a);},oc=a=>{la=a;nc(a)},pc=()=>{if(!(Pa||0<mc))try{var a=la;la=a;nc(a)}catch(b){lc(b)}},qc=a=>{if(!ka)try{a(),pc()}catch(b){lc(b)}},rc;rc=()=>performance.now();
var Dc=(a,b)=>{sc=a;vc=b;if(wc)if(xc||=!0,0==a)yc=function(){var d=Math.max(0,zc+b-rc())|0;setTimeout(Ac,d)};else if(1==a)yc=function(){Bc(Ac)};else if(2==a){if("undefined"==typeof Cc)if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Cc=d=>{c.push(d);postMessage("setimmediate","*")}}else Cc=setImmediate;yc=function(){Cc(Ac)}}},Lc=a=>{function b(){return c<Gc?(pc(),!1):!0}wc=a;
var c=Gc;xc=!1;Ac=function(){if(!ka)if(0<Hc.length){var d=Hc.shift();d.Lb(d.Ab);if(Ic){var e=Ic,f=0==e%1?e-1:Math.floor(e);Ic=d.Hb?f:(8*e+(f+.5))/9}h.setStatus&&(d=h.statusMessage||"Please wait...",e=Ic,f=Jc.Jb,e?e<f?h.setStatus("{message} ({expected - remaining}/{expected})"):h.setStatus(d):h.setStatus(""));b()&&setTimeout(Ac,0)}else b()&&(Kc=Kc+1|0,1==sc&&1<vc&&0!=Kc%vc?yc():(0==sc&&(zc=rc()),ka||h.preMainLoop&&!1===h.preMainLoop()||(qc(a),h.postMainLoop?.()),b()&&("object"==typeof SDL&&SDL.audio?.Rb?.(),
yc())))}},Mc=(a,b)=>setTimeout(()=>{qc(a)},b),xc=!1,yc=null,Gc=0,wc=null,sc=0,vc=0,Kc=0,Hc=[];function Nc(){yc=null;Gc++}function Oc(){Gc++;var a=sc,b=vc,c=wc;wc=null;Lc(c);Dc(a,b);yc()}var Jc={},zc,Ac,Ic,Pc=!1,Qc=!1,Rc=[];
function pb(){function a(){Qc=document.pointerLockElement===h.canvas||document.mozPointerLockElement===h.canvas||document.webkitPointerLockElement===h.canvas||document.msPointerLockElement===h.canvas}if(!Sc){Sc=!0;nb.push({canHandle:function(c){return!h.noImageDecoding&&/\.(jpg|jpeg|png|bmp|webp)$/i.test(c)},handle:function(c,d,e,f){var g=new Blob([c],{type:Tc(d)});g.size!==c.length&&(g=new Blob([(new Uint8Array(c)).buffer],{type:Tc(d)}));var m=URL.createObjectURL(g),n=new Image;n.onload=()=>{var p=
document.createElement("canvas");p.width=n.width;p.height=n.height;p.getContext("2d").drawImage(n,0,0);Uc[d]=p;URL.revokeObjectURL(m);e?.(c)};n.onerror=()=>{aa(`Image ${m} could not be decoded`);f?.()};n.src=m}});nb.push({canHandle:function(c){return!h.noAudioDecoding&&c.substr(-4)in{".ogg":1,".wav":1,".mp3":1}},handle:function(c,d,e){function f(){g||(g=!0,e?.(c))}var g=!1,m=URL.createObjectURL(new Blob([c],{type:Tc(d)})),n=new Audio;n.addEventListener("canplaythrough",()=>f(n),!1);n.onerror=function(){if(!g){aa(`warning: browser could not fully decode audio ${d}, trying slower base64 approach`);
for(var p="",t=0,v=0,r=0;r<c.length;r++)for(t=t<<8|c[r],v+=8;6<=v;){var A=t>>v-6&63;v-=6;p+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[A]}2==v?(p+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(t&3)<<4],p+="=="):4==v&&(p+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(t&15)<<2],p+="=");n.src="data:audio/x-"+d.substr(-3)+";base64,"+p;f(n)}};n.src=m;Mc(()=>{f(n)},1E4)}});var b=h.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||
b.webkitRequestPointerLock||b.msRequestPointerLock||(()=>{}),b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||(()=>{}),b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),h.elementPointerLock&&b.addEventListener("click",
c=>{!Qc&&h.canvas.requestPointerLock&&(h.canvas.requestPointerLock(),c.preventDefault())},!1))}}var Vc=!1,Wc=void 0,Xc=void 0;function Yc(){if(!Pc)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||(()=>{})).apply(document,[]);return!0}var Zc=0;
function Bc(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===Zc)Zc=b+1E3/60;else for(;b+2>=Zc;)Zc+=1E3/60;setTimeout(a,Math.max(Zc-b,0))}}function Tc(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]}var $c=[];function ad(){var a=h.canvas;$c.forEach(b=>b(a.width,a.height))}
function bd(a,b,c){b&&c?(a.zb=b,a.ib=c):(b=a.zb,c=a.ib);var d=b,e=c;h.forcedAspectRatio&&0<h.forcedAspectRatio&&(d/e<h.forcedAspectRatio?d=Math.round(e*h.forcedAspectRatio):e=Math.round(d/h.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var f=Math.min(screen.width/d,screen.height/e);d=Math.round(d*f);e=Math.round(e*
f)}Xc?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}
var ob={},Cc,Sc,K=12288,cd=!1,dd=0,ed=0,fd=0,L={alpha:!1,depth:!1,stencil:!1,antialias:!1},gd={},hd,M,jd=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=(c,d,e,f)=>b.drawArraysInstancedANGLE(c,d,e,f),a.drawElementsInstanced=(c,d,e,f,g)=>b.drawElementsInstancedANGLE(c,d,e,f,g))},kd=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),
a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},ld=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},md=a=>{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},nd=1,od=[],N=[],pd=[],qd=[],rd=[],O=[],sd=[],td=[],ud=[],vd={},wd=4,xd=0,yd=a=>{for(var b=nd++,c=a.length;c<b;c++)a[c]=null;return b},zd=(a,b,c,d)=>{for(var e=0;e<a;e++){var f=M[c](),g=f&&yd(d);f?(f.name=g,d[g]=f):P||=1282;q[b+4*e>>2]=g}},Bd=(a,b)=>{a.o||(a.o=a.getContext,a.getContext=function(d,e){e=a.o(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl",b);return c?Ad(c,b):0},Ad=(a,b)=>{var c=
yd(td),d={handle:c,attributes:b,version:b.Ha,M:a};a.canvas&&(a.canvas.T=d);td[c]=d;("undefined"==typeof b.bb||b.bb)&&Cd(d);return c},Ed=a=>{Dd=td[a];h.G=M=Dd?.M},Cd=a=>{a||=Dd;if(!a.kb){a.kb=!0;var b=a.M;b.Pb=b.getExtension("WEBGL_multi_draw");b.eb=b.getExtension("EXT_polygon_offset_clamp");b.cb=b.getExtension("EXT_clip_control");b.yb=b.getExtension("WEBGL_polygon_mode");jd(b);kd(b);ld(b);b.J=b.getExtension("EXT_disjoint_timer_query");md(b).forEach(c=>{c.includes("lose_context")||c.includes("debug")||
b.getExtension(c)})}},Fd={},P,Dd,Gd=a=>{var b=Za(a)+1,c=C(b);c&&E(a,l,c,b);return c},Hd=[],Id=(a,b)=>{Hd.length=0;for(var c;c=l[a++];){var d=105!=c;d&=112!=c;b+=d&&b%8?4:0;Hd.push(112==c?u[b>>2]:105==c?q[b>>2]:x[b>>3]);b+=d?8:4}return Hd},Jd=0,Kd=[];function Ld(a,b,c){function d(f,g){if(f.length!=g.length)return!1;for(var m in f)if(f[m]!=g[m])return!1;return!0}for(var e of Kd)if(e.ta==a&&d(e.wa,c))return;Kd.push({ta:a,La:b,wa:c});Kd.sort((f,g)=>f.La<g.La)}function Md(a){Kd=Kd.filter(b=>b.ta!=a)}
function Nd(){return navigator.userActivation?navigator.userActivation.isActive:Jd&&Od.aa}function Pd(){if(Nd()){var a=Kd;Kd=[];for(var b of a)b.ta(...b.wa)}}var Qd=[];function Rd(a){var b=Qd[a];b.target.removeEventListener(b.u,b.Aa,b.C);Qd.splice(a,1)}function Sd(a){if(!a.target)return-4;if(a.D)a.Aa=function(c){++Jd;Od=a;Pd();a.F(c);Pd();--Jd},a.target.addEventListener(a.u,a.Aa,a.C),Qd.push(a);else for(var b=0;b<Qd.length;++b)Qd[b].target==a.target&&Qd[b].u==a.u&&Rd(b--);return 0}
function Td(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}function Ud(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}
var Vd={},Od,Wd,Xd,Yd,Zd,$d,ae,be,ce,de,ee,fe,ge,he={},ie=[0,document,window],Q=a=>{a=2<a?a?B(l,a):"":a;return ie[a]||document.querySelector(a)},ke=a=>{var b=Za(a)+1,c=je(b);E(a,l,c,b);return c},le=a=>{var b=R(),c=je(8),d=c+4;a=ke(a.id);if(a=Q(a))q[c>>2]=a.width,q[d>>2]=a.height;c=[q[c>>2],q[d>>2]];U(b);return c},me=(a,b,c)=>{a=Q(a);if(!a)return-4;a.width=b;a.height=c;return 0},ne=(a,b,c)=>{if(a.Gb){var d=R();a=ke(a.id);me(a,b,c);U(d)}else a.width=b,a.height=c},oe=a=>{function b(){document.fullscreenElement||
document.webkitFullscreenElement||(document.removeEventListener("fullscreenchange",b),document.removeEventListener("webkitfullscreenchange",b),ne(a,d,e),a.style.width=f,a.style.height=g,a.style.backgroundColor=m,n||(document.body.style.backgroundColor="white"),document.body.style.backgroundColor=n,a.style.paddingLeft=p,a.style.paddingRight=t,a.style.paddingTop=v,a.style.paddingBottom=r,a.style.marginLeft=A,a.style.marginRight=D,a.style.marginTop=H,a.style.marginBottom=T,document.body.style.margin=
va,document.documentElement.style.overflow=tc,document.body.scroll=uc,a.style.O=Y,a.T&&a.T.M.viewport(0,0,d,e),he.ba&&V(he.ba,37,0,he.xa))}var c=le(a),d=c[0],e=c[1],f=a.style.width,g=a.style.height,m=a.style.backgroundColor,n=document.body.style.backgroundColor,p=a.style.paddingLeft,t=a.style.paddingRight,v=a.style.paddingTop,r=a.style.paddingBottom,A=a.style.marginLeft,D=a.style.marginRight,H=a.style.marginTop,T=a.style.marginBottom,va=document.body.style.margin,tc=document.documentElement.style.overflow,
uc=document.body.scroll,Y=a.style.O;document.addEventListener("fullscreenchange",b);document.addEventListener("webkitfullscreenchange",b)},pe=(a,b,c)=>{a.style.paddingLeft=a.style.paddingRight=c+"px";a.style.paddingTop=a.style.paddingBottom=b+"px"},qe=a=>0>ie.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},re=(a,b)=>{if(0!=b.sa||0!=b.ma){oe(a);var c=b.wb?innerWidth:screen.width,d=b.wb?innerHeight:screen.height,e=qe(a),f=e.width;e=e.height;var g=le(a),m=g[0];g=g[1];3==b.sa?(pe(a,(d-e)/2,(c-f)/
2),c=f,d=e):2==b.sa&&(c*g<m*d?(f=g*c/m,pe(a,(d-f)/2,0),d=f):(f=m*d/g,pe(a,0,(c-f)/2),c=f));a.style.backgroundColor||(a.style.backgroundColor="black");document.body.style.backgroundColor||(document.body.style.backgroundColor="black");a.style.width=c+"px";a.style.height=d+"px";1==b.fb&&(a.style.O="optimizeSpeed",a.style.O="-moz-crisp-edges",a.style.O="-o-crisp-edges",a.style.O="-webkit-optimize-contrast",a.style.O="optimize-contrast",a.style.O="crisp-edges",a.style.O="pixelated");f=2==b.ma?devicePixelRatio:
1;0!=b.ma&&(c=c*f|0,d=d*f|0,ne(a,c,d),a.T&&a.T.M.viewport(0,0,c,d))}if(a.requestFullscreen)a.requestFullscreen();else if(a.webkitRequestFullscreen)a.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT);else return Ud()?-3:-1;he=b;b.ba&&V(b.ba,37,0,b.xa);return 0},se=a=>{if(a.requestPointerLock)a.requestPointerLock();else return document.body.requestPointerLock?-3:-1;return 0},te=(a,b)=>{x[a>>3]=b.timestamp;for(var c=0;c<b.axes.length;++c)x[a+8*c+16>>3]=b.axes[c];for(c=0;c<b.buttons.length;++c)x[a+
8*c+528>>3]="object"==typeof b.buttons[c]?b.buttons[c].value:b.buttons[c];for(c=0;c<b.buttons.length;++c)k[a+c+1040]="object"==typeof b.buttons[c]?b.buttons[c].pressed:1==b.buttons[c];k[a+1104]=b.connected;q[a+1108>>2]=b.index;q[a+8>>2]=b.axes.length;q[a+12>>2]=b.buttons.length;E(b.id,l,a+1112,64);E(b.mapping,l,a+1176,64)},ue=(a,b,c)=>{a=Wa(a);a=Uc[a];if(!a)return 0;var d=a.getContext("2d").getImageData(0,0,a.width,a.height),e=C(a.width*a.height*4);l.set(d.data,e);q[b>>2]=a.width;q[c>>2]=a.height;
return e},ve=[],we=(a,b,c,d,e,f,g,m)=>{b=N[b];if(a=M[a](b,c))d=m&&E(a.name,l,m,d),e&&(q[e>>2]=d),f&&(q[f>>2]=a.size),g&&(q[g>>2]=a.type)},xe=(a,b,c)=>{if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:0!=c&&1!=c&&(P||=1280);return;case 36345:d=0;break;case 34466:var e=M.getParameter(34467);d=e?e.length:0}if(void 0===d)switch(e=M.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":P||=1280;return;case "object":if(null===e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:d=
0;break;default:P||=1280;return}else{if(e instanceof Float32Array||e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:q[b+4*a>>2]=e[a];break;case 2:w[b+4*a>>2]=e[a];break;case 4:k[b+a]=e[a]?1:0}return}try{d=e.name|0}catch(f){P||=1280;aa(`GL_INVALID_ENUM in glGet${c}v: Unknown object returned from WebGL getParameter(${a})! (error: ${f})`);return}}break;default:P||=1280;aa(`GL_INVALID_ENUM in glGet${c}v: Native code calling glGet${c}v(${a}) and it returns ${e} of type ${typeof e}!`);
return}switch(c){case 1:c=d;u[b>>2]=c;u[b+4>>2]=(c-u[b>>2])/4294967296;break;case 0:q[b>>2]=d;break;case 2:w[b>>2]=d;break;case 4:k[b]=d?1:0}}else P||=1281},ye=(a,b,c)=>{if(c){a=M.J.getQueryObjectEXT(ud[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;u[c>>2]=d;u[c+4>>2]=(d-u[c>>2])/4294967296}else P||=1281},ze=(a,b,c)=>{if(c){a=M.J.getQueryObjectEXT(ud[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;q[c>>2]=d}else P||=1281};function Ae(){var a=md(M);return a=a.concat(a.map(b=>"GL_"+b))}
var Be=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),De=a=>{var b=a.$,c=a.Pa,d;if(!b){a.$=b={};a.Oa={};var e=M.getProgramParameter(a,35718);for(d=0;d<e;++d){var f=M.getActiveUniform(a,d);var g=f.name;f=f.size;var m=Be(g);m=0<m?g.slice(0,m):g;var n=a.ua;a.ua+=f;c[m]=[f,n];for(g=0;g<f;++g)b[n]=g,a.Oa[n++]=m}}},W=a=>{var b=M.Wa;if(b){var c=b.$[a];"number"==typeof c&&(b.$[a]=c=M.getUniformLocation(b,b.Oa[a]+(0<c?`[${c}]`:"")));return c}P||=1282},Ee=(a,b,c,d)=>{if(c)if(a=N[a],De(a),a=M.getUniform(a,W(b)),"number"==
typeof a||"boolean"==typeof a)switch(d){case 0:q[c>>2]=a;break;case 2:w[c>>2]=a}else for(b=0;b<a.length;b++)switch(d){case 0:q[c+4*b>>2]=a[b];break;case 2:w[c+4*b>>2]=a[b]}else P||=1281},Fe=(a,b,c,d)=>{if(c)if(a=M.getVertexAttrib(a,b),34975==b)q[c>>2]=a&&a.name;else if("number"==typeof a||"boolean"==typeof a)switch(d){case 0:q[c>>2]=a;break;case 2:w[c>>2]=a;break;case 5:q[c>>2]=Math.fround(a)}else for(b=0;b<a.length;b++)switch(d){case 0:q[c+4*b>>2]=a[b];break;case 2:w[c+4*b>>2]=a[b];break;case 5:q[c+
4*b>>2]=Math.fround(a[b])}else P||=1281},Ge=(a,b,c,d,e)=>{a-=5120;a=1==a?l:4==a?q:6==a?w:5==a||28922==a?u:na;b=d*((xd||c)*({5:3,6:4,8:2,29502:3,29504:4}[b-6402]||1)*a.BYTES_PER_ELEMENT+wd-1&-wd);return a.subarray(e>>>31-Math.clz32(a.BYTES_PER_ELEMENT),e+b>>>31-Math.clz32(a.BYTES_PER_ELEMENT))},He=[],Ie=[],Je=(a,b)=>{if(!Ud())return-1;a=Q(a);return a?a.requestFullscreen||a.webkitRequestFullscreen?Nd()?re(a,b):b.$a?(Ld(re,1,[a,b]),1):-2:-3:-4},Ke=()=>{try{if(navigator.getGamepads)return(Wd=navigator.getGamepads())?
0:-1}catch(a){navigator.getGamepads=null}return-1},Le=(a,b)=>{var c={target:Q(2),u:"beforeunload",D:b,F:(d=event)=>{var e=V(b,28,0,a);e&&=e?B(l,e):"";if(e)return d.preventDefault(),d.returnValue=e},C:!0};return Sd(c)},Me=(a,b,c,d,e,f)=>{Xd||=C(256);a={target:Q(a),u:f,D:d,F:(g=event)=>{var m=g.target.id?g.target.id:"",n=Xd;E(Td(g.target),l,n+0,128);E(m,l,n+128,128);V(d,e,n,b)&&g.preventDefault()},C:c};return Sd(a)},Ne=(a,b,c,d,e)=>{Zd||=C(276);return Sd({target:a,u:e,D:d,F:(f=event)=>{var g=Zd,m=document.fullscreenElement||
document.mozFullScreenElement||document.webkitFullscreenElement||document.msFullscreenElement,n=!!m;k[g]=n;k[g+1]=Ud();var p=n?m:Yd,t=p?.id||"";E(Td(p),l,g+2,128);E(t,l,g+130,128);q[g+260>>2]=p?p.clientWidth:0;q[g+264>>2]=p?p.clientHeight:0;q[g+268>>2]=screen.width;q[g+272>>2]=screen.height;n&&(Yd=m);V(d,19,g,b)&&f.preventDefault()},C:c})},Oe=(a,b,c,d,e)=>{$d||=C(1240);b={target:Q(2),aa:!0,u:e,D:c,F:(f=event)=>{var g=$d;te(g,f.gamepad);V(c,d,g,a)&&f.preventDefault()},C:b};return Sd(b)},Pe=(a,b,c,
d,e,f)=>{ae||=C(160);a={target:Q(a),u:f,D:d,F:g=>{var m=ae;x[m>>3]=g.timeStamp;var n=m>>2;q[n+2]=g.location;k[m+12]=g.ctrlKey;k[m+13]=g.shiftKey;k[m+14]=g.altKey;k[m+15]=g.metaKey;k[m+16]=g.repeat;q[n+5]=g.charCode;q[n+6]=g.keyCode;q[n+7]=g.which;E(g.key||"",l,m+32,32);E(g.code||"",l,m+64,32);E(g.char||"",l,m+96,32);E(g.locale||"",l,m+128,32);V(d,e,m,b)&&g.preventDefault()},C:c};return Sd(a)},Qe=(a,b,c)=>{x[a>>3]=b.timeStamp;var d=a>>2;q[d+2]=b.screenX;q[d+3]=b.screenY;q[d+4]=b.clientX;q[d+5]=b.clientY;
k[a+24]=b.ctrlKey;k[a+25]=b.shiftKey;k[a+26]=b.altKey;k[a+27]=b.metaKey;ma[2*d+14]=b.button;ma[2*d+15]=b.buttons;q[d+8]=b.movementX;q[d+9]=b.movementY;a=qe(c);q[d+10]=b.clientX-(a.left|0);q[d+11]=b.clientY-(a.top|0)},Re=(a,b,c,d,e,f)=>{be||=C(64);a=Q(a);return Sd({target:a,aa:"mousemove"!=f&&"mouseenter"!=f&&"mouseleave"!=f,u:f,D:d,F:(g=event)=>{Qe(be,g,a);V(d,e,be,b)&&g.preventDefault()},C:c})},Se=(a,b,c,d,e)=>{ce||=C(257);return Sd({target:a,u:e,D:d,F:(f=event)=>{var g=ce,m=document.pointerLockElement||
document.o||document.qb||document.oa;k[g]=!!m;var n=m?.id||"";E(Td(m),l,g+1,128);E(n,l,g+129,128);V(d,20,g,b)&&f.preventDefault()},C:c})},Te=(a,b,c,d)=>{de||=C(36);a=Q(a);return Sd({target:a,u:"resize",D:d,F:(e=event)=>{if(e.target==a){var f=document.body;if(f){var g=de;q[g>>2]=0;q[g+4>>2]=f.clientWidth;q[g+8>>2]=f.clientHeight;q[g+12>>2]=innerWidth;q[g+16>>2]=innerHeight;q[g+20>>2]=outerWidth;q[g+24>>2]=outerHeight;q[g+28>>2]=pageXOffset|0;q[g+32>>2]=pageYOffset|0;V(d,10,g,b)&&e.preventDefault()}}},
C:c})},Ue=(a,b,c,d,e,f)=>{ee||=C(1552);a=Q(a);return Sd({target:a,aa:"touchstart"==f||"touchend"==f,u:f,D:d,F:g=>{var m={},n=g.touches;for(var p of n)p.Ea=p.Ka=0,m[p.identifier]=p;for(var t of g.changedTouches)t.Ea=1,m[t.identifier]=t;for(var v of g.targetTouches)m[v.identifier].Ka=1;n=ee;x[n>>3]=g.timeStamp;k[n+12]=g.ctrlKey;k[n+13]=g.shiftKey;k[n+14]=g.altKey;k[n+15]=g.metaKey;p=n+16;t=qe(a);v=0;for(let r of Object.values(m))if(m=p>>2,q[m]=r.identifier,q[m+1]=r.screenX,q[m+2]=r.screenY,q[m+3]=r.clientX,
q[m+4]=r.clientY,q[m+5]=r.pageX,q[m+6]=r.pageY,k[p+28]=r.Ea,k[p+29]=r.Ka,q[m+8]=r.clientX-(t.left|0),q[m+9]=r.clientY-(t.top|0),p+=48,31<++v)break;q[n+8>>2]=v;V(d,e,n,b)&&g.preventDefault()},C:c})},Ve=(a,b,c)=>{var d=ie[1];fe||=C(8);return Sd({target:d,u:"visibilitychange",D:c,F:(e=event)=>{var f=fe,g=["hidden","visible","prerender","unloaded"].indexOf(document.visibilityState);k[f]=document.hidden;q[f+4>>2]=g;V(c,21,f,a)&&e.preventDefault()},C:b})},We=(a,b,c,d)=>{ge||=C(96);return Sd({target:a,aa:!0,
u:"wheel",D:d,F:(e=event)=>{var f=ge;Qe(f,e,a);x[f+64>>3]=e.deltaX;x[f+72>>3]=e.deltaY;x[f+80>>3]=e.deltaZ;q[f+88>>2]=e.deltaMode;V(d,9,f,b)&&e.preventDefault()},C:c})},Xe={},Ze=()=>{if(!Ye){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:da||"./this.program"},b;for(b in Xe)void 0===Xe[b]?delete a[b]:a[b]=Xe[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);
Ye=c}return Ye},Ye,$e=(a,b,c)=>{a.addEventListener(b,c,{once:!0})},Ja=a=>{var b;b||=[document,document.getElementById("canvas")];["keydown","mousedown","touchstart"].forEach(c=>{b.forEach(d=>{d&&$e(d,c,()=>{"suspended"===a.state&&a.resume()})})})},Ka=(a,b=[])=>{var c="vi".replace(/p/g,"i");(0,h["dynCall_"+c])(a,...b)},af=a=>{try{a()}catch(b){za(b)}};
function bf(){var a=X,b={};for(let [c,d]of Object.entries(a))b[c]="function"==typeof d?(...e)=>{cf.push(c);try{return d(...e)}finally{ka||(cf.pop(),df&&1===ef&&0===cf.length&&(ef=0,af(ff),"undefined"!=typeof Fibers&&Fibers.Tb()))}}:d;return b}var ef=0,df=null,gf=0,cf=[],hf={},jf={},kf=0,lf=null,mf=[];function nf(){var a=C(4108),b=a+12;u[a>>2]=b;u[a+4>>2]=b+4096;b=cf[0];var c=hf[b];void 0===c&&(c=kf++,hf[b]=c,jf[c]=b);q[a+8>>2]=c;return a}
function of(a){if(!ka){if(0===ef){var b=!1,c=!1;a((d=0)=>{if(!ka&&(gf=d,b=!0,c)){ef=2;af(()=>pf(df));"undefined"!=typeof ob&&wc&&Oc();d=!1;try{var e=(0,X[jf[q[df+8>>2]]])()}catch(m){e=m,d=!0}var f=!1;if(!df){var g=lf;g&&(lf=null,(d?g.reject:g.resolve)(e),f=!0)}if(d&&!f)throw e;}});c=!0;b||(ef=1,df=nf(),"undefined"!=typeof ob&&wc&&Nc(),af(()=>qf(df)))}else 2===ef?(ef=0,af(rf),sf(df),df=null,mf.forEach(qc)):za(`invalid state: ${ef}`);return gf}}
var Ia=0,Ga=(a,b)=>{b=1==b?je(a.length):C(a.length);a.subarray||a.slice||(a=new Uint8Array(a));l.set(a,b);return b};[44].forEach(a=>{kb[a]=new F(a);kb[a].stack="<generic error, no stack>"});yb=Array(4096);Ob(G,"/");Qb("/tmp");Qb("/home");Qb("/home/web_user");
(function(){Qb("/dev");bb(259,{read:()=>0,write:(d,e,f,g)=>g});Rb("/dev/null",259);ab(1280,db);ab(1536,eb);Rb("/dev/tty",1280);Rb("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(b=Va(a).byteLength);return a[--b]};dc("/dev","random",c);dc("/dev","urandom",c);Qb("/dev/shm");Qb("/dev/shm/tmp")})();
(function(){Qb("/proc");var a=Qb("/proc/self");Qb("/proc/self/fd");Ob({K(){var b=jb(a,"fd",16895,73);b.h={V(c,d){var e=Lb(+d);c={parent:null,K:{Ia:"fake"},h:{Y:()=>e.path}};return c.parent=c}};return b}},"/proc/self/fd")})();h.FS_createPath=bc;h.FS_createDataFile=rb;h.FS_createPreloadedFile=sb;h.FS_unlink=Tb;h.FS_createLazyFile=fc;h.FS_createDevice=dc;
h.requestFullscreen=function(a,b){function c(){Pc=!1;var f=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===f?(d.exitFullscreen=Yc,Wc&&d.requestPointerLock(),Pc=!0,Xc?("undefined"!=typeof SDL&&(q[SDL.screen>>2]=u[SDL.screen>>2]|8388608),bd(h.canvas),ad()):bd(d)):(f.parentNode.insertBefore(d,f),f.parentNode.removeChild(f),Xc?("undefined"!=typeof SDL&&(q[SDL.screen>>2]=
u[SDL.screen>>2]&-8388609),bd(h.canvas),ad()):bd(d));h.onFullScreen?.(Pc);h.onFullscreen?.(Pc)}Wc=a;Xc=b;"undefined"==typeof Wc&&(Wc=!0);"undefined"==typeof Xc&&(Xc=!1);var d=h.canvas;Vc||(Vc=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);e.requestFullscreen=
e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?()=>e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT):null)||(e.webkitRequestFullScreen?()=>e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):null);e.requestFullscreen()};h.requestAnimationFrame=Bc;h.setCanvasSize=function(a,b,c){bd(h.canvas,a,b);c||ad()};h.pauseMainLoop=Nc;h.resumeMainLoop=Oc;
h.getUserMedia=function(a){let b;(b=window).getUserMedia||(b.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(a)};h.createContext=function(a,b,c,d){if(b&&h.G&&a==h.canvas)return h.G;var e;if(b){var f={antialias:!1,alpha:!1,Ha:1};if(d)for(var g in d)f[g]=d[g];if("undefined"!=typeof Fd&&(e=Bd(a,f)))var m=td[e].M}else m=a.getContext("2d");if(!m)return null;c&&(h.G=m,b&&Ed(e),Rc.forEach(n=>n()),pb());return m};for(var Uc={},Z=0;32>Z;++Z)ve.push(Array(Z));var tf=new Float32Array(288);
for(Z=0;288>=Z;++Z)He[Z]=tf.subarray(0,Z);var uf=new Int32Array(288);for(Z=0;288>=Z;++Z)Ie[Z]=uf.subarray(0,Z);
var Hf={__call_sighandler:(a,b)=>dynCall_vi(a,b),__syscall__newselect:function(a,b,c,d,e){try{for(var f=0,g=b?q[b>>2]:0,m=b?q[b+4>>2]:0,n=c?q[c>>2]:0,p=c?q[c+4>>2]:0,t=d?q[d>>2]:0,v=d?q[d+4>>2]:0,r=0,A=0,D=0,H=0,T=0,va=0,tc=(b?q[b>>2]:0)|(c?q[c>>2]:0)|(d?q[d>>2]:0),uc=(b?q[b+4>>2]:0)|(c?q[c+4>>2]:0)|(d?q[d+4>>2]:0),Y=0;Y<a;Y++){var S=1<<Y%32;if(32>Y?tc&S:uc&S){var Ec=Lb(Y),Ib=5;if(Ec.i.ub){var Ce=-1;e&&(Ce=1E3*((b?q[e>>2]:0)+(b?q[e+4>>2]:0)/1E6));Ib=Ec.i.ub(Ec,Ce)}Ib&1&&(32>Y?g&S:m&S)&&(32>Y?r|=S:
A|=S,f++);Ib&4&&(32>Y?n&S:p&S)&&(32>Y?D|=S:H|=S,f++);Ib&2&&(32>Y?t&S:v&S)&&(32>Y?T|=S:va|=S,f++)}}b&&(q[b>>2]=r,q[b+4>>2]=A);c&&(q[c>>2]=D,q[c+4>>2]=H);d&&(q[d>>2]=T,q[d+4>>2]=va);return f}catch(Fc){if("undefined"==typeof J||"ErrnoError"!==Fc.name)throw Fc;return-Fc.s}},__syscall_fcntl64:function(a,b,c){ic=c;try{var d=Lb(a);switch(b){case 0:var e=jc();if(0>e)break;for(;wb[e];)e++;return Nb(d,e).N;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=jc(),d.flags|=e,0;case 12:return e=jc(),
ma[e+0>>1]=2,0;case 13:case 14:return 0}return-28}catch(f){if("undefined"==typeof J||"ErrnoError"!==f.name)throw f;return-f.s}},__syscall_fstat64:function(a,b){try{var c=Lb(a);return hc(Ub,c.path,b)}catch(d){if("undefined"==typeof J||"ErrnoError"!==d.name)throw d;return-d.s}},__syscall_getdents64:function(a,b,c){try{var d=Lb(a);if(!d.P){var e=Db(d.path,{U:!0}).node;if(!e.h.ia)throw new F(54);var f=e.h.ia(e);d.P=f}a=0;for(var g=$b(d,0,1),m=Math.floor(g/280);m<d.P.length&&a+280<=c;){var n=d.P[m];if("."===
n){var p=d.node.id;var t=4}else if(".."===n)p=Db(d.path,{parent:!0}).node.id,t=4;else{var v=lb(d.node,n);p=v.id;t=8192===(v.mode&61440)?2:I(v.mode)?4:40960===(v.mode&61440)?10:8}z=[p>>>0,(y=p,1<=+Math.abs(y)?0<y?+Math.floor(y/4294967296)>>>0:~~+Math.ceil((y-+(~~y>>>0))/4294967296)>>>0:0)];q[b+a>>2]=z[0];q[b+a+4>>2]=z[1];z=[280*(m+1)>>>0,(y=280*(m+1),1<=+Math.abs(y)?0<y?+Math.floor(y/4294967296)>>>0:~~+Math.ceil((y-+(~~y>>>0))/4294967296)>>>0:0)];q[b+a+8>>2]=z[0];q[b+a+12>>2]=z[1];ma[b+a+16>>1]=280;
k[b+a+18]=t;E(n,l,b+a+19,256);a+=280;m+=1}$b(d,280*m,0);return a}catch(r){if("undefined"==typeof J||"ErrnoError"!==r.name)throw r;return-r.s}},__syscall_ioctl:function(a,b,c){ic=c;try{var d=Lb(a);switch(b){case 21509:return d.j?0:-59;case 21505:if(!d.j)return-59;if(d.j.L.mb){a=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var e=jc();q[e>>2]=25856;q[e+4>>2]=5;q[e+8>>2]=191;q[e+12>>2]=35387;for(var f=0;32>f;f++)k[e+f+17]=a[f]||0}return 0;case 21510:case 21511:case 21512:return d.j?
0:-59;case 21506:case 21507:case 21508:if(!d.j)return-59;if(d.j.L.nb)for(e=jc(),a=[],f=0;32>f;f++)a.push(k[e+f+17]);return 0;case 21519:if(!d.j)return-59;e=jc();return q[e>>2]=0;case 21520:return d.j?-28:-59;case 21531:e=jc();if(!d.i.lb)throw new F(59);return d.i.lb(d,b,e);case 21523:if(!d.j)return-59;d.j.L.ob&&(f=[24,80],e=jc(),ma[e>>1]=f[0],ma[e+2>>1]=f[1]);return 0;case 21524:return d.j?0:-59;case 21515:return d.j?0:-59;default:return-28}}catch(g){if("undefined"==typeof J||"ErrnoError"!==g.name)throw g;
return-g.s}},__syscall_lstat64:function(a,b){try{return a=a?B(l,a):"",hc(Vb,a,b)}catch(c){if("undefined"==typeof J||"ErrnoError"!==c.name)throw c;return-c.s}},__syscall_newfstatat:function(a,b,c,d){try{b=b?B(l,b):"";var e=d&256;b=gc(a,b,d&4096);return hc(e?Vb:Ub,b,c)}catch(f){if("undefined"==typeof J||"ErrnoError"!==f.name)throw f;return-f.s}},__syscall_openat:function(a,b,c,d){ic=d;try{b=b?B(l,b):"";b=gc(a,b);var e=d?jc():0;return Xb(b,c,e).N}catch(f){if("undefined"==typeof J||"ErrnoError"!==f.name)throw f;
return-f.s}},__syscall_stat64:function(a,b){try{return a=a?B(l,a):"",hc(Ub,a,b)}catch(c){if("undefined"==typeof J||"ErrnoError"!==c.name)throw c;return-c.s}},_abort_js:()=>{za("")},_emscripten_get_now_is_monotonic:()=>1,_emscripten_memcpy_js:(a,b,c)=>l.copyWithin(a,b,b+c),_emscripten_runtime_keepalive_clear:()=>{Pa=!1;mc=0},_emscripten_throw_longjmp:()=>{throw Infinity;},_setitimer_js:(a,b)=>{kc[a]&&(clearTimeout(kc[a].id),delete kc[a]);if(!b)return 0;var c=setTimeout(()=>{delete kc[a];qc(()=>vf(a,
rc()))},b);kc[a]={id:c,Sb:b};return 0},eglBindAPI:a=>{if(12448==a)return K=12288,1;K=12300;return 0},eglChooseConfig:(a,b,c,d,e)=>{if(62E3!=a)K=12296,c=0;else{if(b)for(;;){a=q[b>>2];if(12321==a)L.alpha=0<q[b+4>>2];else if(12325==a)L.depth=0<q[b+4>>2];else if(12326==a)L.stencil=0<q[b+4>>2];else if(12337==a)a=q[b+4>>2],L.antialias=0<a;else if(12338==a)a=q[b+4>>2],L.antialias=1==a;else if(12544==a)L.Nb=12547!=q[b+4>>2];else if(12344==a)break;b+=8}c&&d||e?(e&&(q[e>>2]=1),c&&0<d&&(u[c>>2]=62002),K=12288,
c=1):(K=12300,c=0)}return c},eglCreateContext:(a,b,c,d)=>{if(62E3!=a)return K=12296,0;for(a=1;;){b=q[d>>2];if(12440==b)a=q[d+4>>2];else if(12344==b)break;else return K=12292,0;d+=8}if(2!=a)return K=12293,0;L.Ha=a-1;L.Ob=0;hd=Bd(h.canvas,L);if(0!=hd)return K=12288,Ed(hd),Rc.forEach(e=>e()),Ed(null),62004;K=12297;return 0},eglCreateWindowSurface:(a,b)=>{if(62E3!=a)return K=12296,0;if(62002!=b)return K=12293,0;K=12288;return 62006},eglDestroyContext:(a,b)=>{if(62E3!=a)return K=12296,0;if(62004!=b)return K=
12294,0;a=hd;Dd===td[a]&&(Dd=null);if("object"==typeof Vd)for(var c=td[a].M.canvas,d=0;d<Qd.length;++d)Qd[d].target!=c||Rd(d--);td[a]&&td[a].M.canvas&&(td[a].M.canvas.T=void 0);td[a]=null;K=12288;dd==b&&(dd=0);return 1},eglDestroySurface:(a,b)=>{if(62E3!=a)return K=12296,0;if(62006!=b)return K=12301,1;ed==b&&(ed=0);fd==b&&(fd=0);K=12288;return 1},eglGetConfigAttrib:(a,b,c,d)=>{if(62E3!=a)return K=12296,0;if(62002!=b)return K=12293,0;if(!d)return K=12300,0;K=12288;switch(c){case 12320:return q[d>>
2]=L.alpha?32:24,1;case 12321:return q[d>>2]=L.alpha?8:0,1;case 12322:return q[d>>2]=8,1;case 12323:return q[d>>2]=8,1;case 12324:return q[d>>2]=8,1;case 12325:return q[d>>2]=L.depth?24:0,1;case 12326:return q[d>>2]=L.stencil?8:0,1;case 12327:return q[d>>2]=12344,1;case 12328:return q[d>>2]=62002,1;case 12329:return q[d>>2]=0,1;case 12330:return q[d>>2]=4096,1;case 12331:return q[d>>2]=16777216,1;case 12332:return q[d>>2]=4096,1;case 12333:return q[d>>2]=0,1;case 12334:return q[d>>2]=0,1;case 12335:return q[d>>
2]=12344,1;case 12337:return q[d>>2]=L.antialias?4:0,1;case 12338:return q[d>>2]=L.antialias?1:0,1;case 12339:return q[d>>2]=4,1;case 12340:return q[d>>2]=12344,1;case 12341:case 12342:case 12343:return q[d>>2]=-1,1;case 12345:case 12346:return q[d>>2]=0,1;case 12347:return q[d>>2]=0,1;case 12348:return q[d>>2]=1;case 12349:case 12350:return q[d>>2]=0,1;case 12351:return q[d>>2]=12430,1;case 12352:return q[d>>2]=4,1;case 12354:return q[d>>2]=0,1;default:return K=12292,0}},eglGetDisplay:a=>{K=12288;
return 0!=a&&1!=a?0:62E3},eglGetError:()=>K,eglInitialize:(a,b,c)=>{if(62E3!=a)return K=12296,0;b&&(q[b>>2]=1);c&&(q[c>>2]=4);cd=!0;K=12288;return 1},eglMakeCurrent:(a,b,c,d)=>{if(62E3!=a)return K=12296,0;if(0!=d&&62004!=d)return K=12294,0;if(0!=c&&62006!=c||0!=b&&62006!=b)return K=12301,0;Ed(d?hd:null);dd=d;fd=b;ed=c;K=12288;return 1},eglQueryString:(a,b)=>{if(62E3!=a)return K=12296,0;K=12288;if(gd[b])return gd[b];switch(b){case 12371:a=Gd("Emscripten");break;case 12372:a=Gd("1.4 Emscripten EGL");
break;case 12373:a=Gd("");break;case 12429:a=Gd("OpenGL_ES");break;default:return K=12300,0}return gd[b]=a},eglSwapBuffers:()=>{if(cd)if(h.G)if(h.G.isContextLost())K=12302;else return K=12288,1;else K=12290;else K=12289;return 0},eglSwapInterval:(a,b)=>{if(62E3!=a)return K=12296,0;0==b?Dc(0,0):Dc(1,b);K=12288;return 1},eglTerminate:a=>{if(62E3!=a)return K=12296,0;fd=ed=dd=0;cd=!1;K=12288;return 1},eglWaitGL:()=>{K=12288;return 1},eglWaitNative:()=>{K=12288;return 1},emscripten_asm_const_int:(a,b,
c)=>{b=Id(b,c);return Ma[a](...b)},emscripten_asm_const_int_sync_on_main_thread:(a,b,c)=>{b=Id(b,c);return Ma[a](...b)},emscripten_asm_const_ptr_sync_on_main_thread:(a,b,c)=>{b=Id(b,c);return Ma[a](...b)},emscripten_cancel_main_loop:()=>{Nc();wc=null},emscripten_date_now:()=>Date.now(),emscripten_exit_fullscreen:()=>{if(!Ud())return-1;Md(re);var a=ie[1];if(a.exitFullscreen)a.fullscreenElement&&a.exitFullscreen();else if(a.webkitExitFullscreen)a.webkitFullscreenElement&&a.webkitExitFullscreen();else return-1;
return 0},emscripten_exit_pointerlock:()=>{Md(se);if(document.exitPointerLock)document.exitPointerLock();else return-1;return 0},emscripten_force_exit:a=>{Pa=!1;mc=0;la=a;nc(a)},emscripten_get_device_pixel_ratio:()=>devicePixelRatio,emscripten_get_element_css_size:(a,b,c)=>{a=Q(a);if(!a)return-4;a=qe(a);x[b>>3]=a.width;x[c>>3]=a.height;return 0},emscripten_get_gamepad_status:(a,b)=>{if(0>a||a>=Wd.length)return-5;if(!Wd[a])return-7;te(b,Wd[a]);return 0},emscripten_get_now:rc,emscripten_get_num_gamepads:()=>
Wd.length,emscripten_get_preloaded_image_data:(a,b,c)=>ue(a?B(l,a):"",b,c),emscripten_get_preloaded_image_data_from_FILE:(a,b,c)=>{a=wf(a);return(a=wb[a])?ue(a.path,b,c):0},emscripten_get_screen_size:(a,b)=>{q[a>>2]=screen.width;q[b>>2]=screen.height},emscripten_glActiveTexture:a=>M.activeTexture(a),emscripten_glAttachShader:(a,b)=>{M.attachShader(N[a],O[b])},emscripten_glBeginQueryEXT:(a,b)=>{M.J.beginQueryEXT(a,ud[b])},emscripten_glBindAttribLocation:(a,b,c)=>{M.bindAttribLocation(N[a],b,c?B(l,
c):"")},emscripten_glBindBuffer:(a,b)=>{M.bindBuffer(a,od[b])},emscripten_glBindFramebuffer:(a,b)=>{M.bindFramebuffer(a,pd[b])},emscripten_glBindRenderbuffer:(a,b)=>{M.bindRenderbuffer(a,qd[b])},emscripten_glBindTexture:(a,b)=>{M.bindTexture(a,rd[b])},emscripten_glBindVertexArrayOES:a=>{M.bindVertexArray(sd[a])},emscripten_glBlendColor:(a,b,c,d)=>M.blendColor(a,b,c,d),emscripten_glBlendEquation:a=>M.blendEquation(a),emscripten_glBlendEquationSeparate:(a,b)=>M.blendEquationSeparate(a,b),emscripten_glBlendFunc:(a,
b)=>M.blendFunc(a,b),emscripten_glBlendFuncSeparate:(a,b,c,d)=>M.blendFuncSeparate(a,b,c,d),emscripten_glBufferData:(a,b,c,d)=>{M.bufferData(a,c?l.subarray(c,c+b):b,d)},emscripten_glBufferSubData:(a,b,c,d)=>{M.bufferSubData(a,b,l.subarray(d,d+c))},emscripten_glCheckFramebufferStatus:a=>M.checkFramebufferStatus(a),emscripten_glClear:a=>M.clear(a),emscripten_glClearColor:(a,b,c,d)=>M.clearColor(a,b,c,d),emscripten_glClearDepthf:a=>M.clearDepth(a),emscripten_glClearStencil:a=>M.clearStencil(a),emscripten_glClipControlEXT:(a,
b)=>{M.cb.clipControlEXT(a,b)},emscripten_glColorMask:(a,b,c,d)=>{M.colorMask(!!a,!!b,!!c,!!d)},emscripten_glCompileShader:a=>{M.compileShader(O[a])},emscripten_glCompressedTexImage2D:(a,b,c,d,e,f,g,m)=>{M.compressedTexImage2D(a,b,c,d,e,f,l.subarray(m,m+g))},emscripten_glCompressedTexSubImage2D:(a,b,c,d,e,f,g,m,n)=>{M.compressedTexSubImage2D(a,b,c,d,e,f,g,l.subarray(n,n+m))},emscripten_glCopyTexImage2D:(a,b,c,d,e,f,g,m)=>M.copyTexImage2D(a,b,c,d,e,f,g,m),emscripten_glCopyTexSubImage2D:(a,b,c,d,e,
f,g,m)=>M.copyTexSubImage2D(a,b,c,d,e,f,g,m),emscripten_glCreateProgram:()=>{var a=yd(N),b=M.createProgram();b.name=a;b.fa=b.da=b.ea=0;b.ua=1;N[a]=b;return a},emscripten_glCreateShader:a=>{var b=yd(O);O[b]=M.createShader(a);return b},emscripten_glCullFace:a=>M.cullFace(a),emscripten_glDeleteBuffers:(a,b)=>{for(var c=0;c<a;c++){var d=q[b+4*c>>2],e=od[d];e&&(M.deleteBuffer(e),e.name=0,od[d]=null)}},emscripten_glDeleteFramebuffers:(a,b)=>{for(var c=0;c<a;++c){var d=q[b+4*c>>2],e=pd[d];e&&(M.deleteFramebuffer(e),
e.name=0,pd[d]=null)}},emscripten_glDeleteProgram:a=>{if(a){var b=N[a];b?(M.deleteProgram(b),b.name=0,N[a]=null):P||=1281}},emscripten_glDeleteQueriesEXT:(a,b)=>{for(var c=0;c<a;c++){var d=q[b+4*c>>2],e=ud[d];e&&(M.J.deleteQueryEXT(e),ud[d]=null)}},emscripten_glDeleteRenderbuffers:(a,b)=>{for(var c=0;c<a;c++){var d=q[b+4*c>>2],e=qd[d];e&&(M.deleteRenderbuffer(e),e.name=0,qd[d]=null)}},emscripten_glDeleteShader:a=>{if(a){var b=O[a];b?(M.deleteShader(b),O[a]=null):P||=1281}},emscripten_glDeleteTextures:(a,
b)=>{for(var c=0;c<a;c++){var d=q[b+4*c>>2],e=rd[d];e&&(M.deleteTexture(e),e.name=0,rd[d]=null)}},emscripten_glDeleteVertexArraysOES:(a,b)=>{for(var c=0;c<a;c++){var d=q[b+4*c>>2];M.deleteVertexArray(sd[d]);sd[d]=null}},emscripten_glDepthFunc:a=>M.depthFunc(a),emscripten_glDepthMask:a=>{M.depthMask(!!a)},emscripten_glDepthRangef:(a,b)=>M.depthRange(a,b),emscripten_glDetachShader:(a,b)=>{M.detachShader(N[a],O[b])},emscripten_glDisable:a=>M.disable(a),emscripten_glDisableVertexAttribArray:a=>{M.disableVertexAttribArray(a)},
emscripten_glDrawArrays:(a,b,c)=>{M.drawArrays(a,b,c)},emscripten_glDrawArraysInstancedANGLE:(a,b,c,d)=>{M.drawArraysInstanced(a,b,c,d)},emscripten_glDrawBuffersWEBGL:(a,b)=>{for(var c=ve[a],d=0;d<a;d++)c[d]=q[b+4*d>>2];M.drawBuffers(c)},emscripten_glDrawElements:(a,b,c,d)=>{M.drawElements(a,b,c,d)},emscripten_glDrawElementsInstancedANGLE:(a,b,c,d,e)=>{M.drawElementsInstanced(a,b,c,d,e)},emscripten_glEnable:a=>M.enable(a),emscripten_glEnableVertexAttribArray:a=>{M.enableVertexAttribArray(a)},emscripten_glEndQueryEXT:a=>
{M.J.endQueryEXT(a)},emscripten_glFinish:()=>M.finish(),emscripten_glFlush:()=>M.flush(),emscripten_glFramebufferRenderbuffer:(a,b,c,d)=>{M.framebufferRenderbuffer(a,b,c,qd[d])},emscripten_glFramebufferTexture2D:(a,b,c,d,e)=>{M.framebufferTexture2D(a,b,c,rd[d],e)},emscripten_glFrontFace:a=>M.frontFace(a),emscripten_glGenBuffers:(a,b)=>{zd(a,b,"createBuffer",od)},emscripten_glGenFramebuffers:(a,b)=>{zd(a,b,"createFramebuffer",pd)},emscripten_glGenQueriesEXT:(a,b)=>{for(var c=0;c<a;c++){var d=M.J.createQueryEXT();
if(!d){for(P||=1282;c<a;)q[b+4*c++>>2]=0;break}var e=yd(ud);d.name=e;ud[e]=d;q[b+4*c>>2]=e}},emscripten_glGenRenderbuffers:(a,b)=>{zd(a,b,"createRenderbuffer",qd)},emscripten_glGenTextures:(a,b)=>{zd(a,b,"createTexture",rd)},emscripten_glGenVertexArraysOES:(a,b)=>{zd(a,b,"createVertexArray",sd)},emscripten_glGenerateMipmap:a=>M.generateMipmap(a),emscripten_glGetActiveAttrib:(a,b,c,d,e,f,g)=>{we("getActiveAttrib",a,b,c,d,e,f,g)},emscripten_glGetActiveUniform:(a,b,c,d,e,f,g)=>{we("getActiveUniform",
a,b,c,d,e,f,g)},emscripten_glGetAttachedShaders:(a,b,c,d)=>{a=M.getAttachedShaders(N[a]);var e=a.length;e>b&&(e=b);q[c>>2]=e;for(b=0;b<e;++b)q[d+4*b>>2]=O.indexOf(a[b])},emscripten_glGetAttribLocation:(a,b)=>M.getAttribLocation(N[a],b?B(l,b):""),emscripten_glGetBooleanv:(a,b)=>xe(a,b,4),emscripten_glGetBufferParameteriv:(a,b,c)=>{c?q[c>>2]=M.getBufferParameter(a,b):P||=1281},emscripten_glGetError:()=>{var a=M.getError()||P;P=0;return a},emscripten_glGetFloatv:(a,b)=>xe(a,b,2),emscripten_glGetFramebufferAttachmentParameteriv:(a,
b,c,d)=>{a=M.getFramebufferAttachmentParameter(a,b,c);if(a instanceof WebGLRenderbuffer||a instanceof WebGLTexture)a=a.name|0;q[d>>2]=a},emscripten_glGetIntegerv:(a,b)=>xe(a,b,0),emscripten_glGetProgramInfoLog:(a,b,c,d)=>{a=M.getProgramInfoLog(N[a]);null===a&&(a="(unknown error)");b=0<b&&d?E(a,l,d,b):0;c&&(q[c>>2]=b)},emscripten_glGetProgramiv:(a,b,c)=>{if(c)if(a>=nd)P||=1281;else if(a=N[a],35716==b)a=M.getProgramInfoLog(a),null===a&&(a="(unknown error)"),q[c>>2]=a.length+1;else if(35719==b){if(!a.fa){var d=
M.getProgramParameter(a,35718);for(b=0;b<d;++b)a.fa=Math.max(a.fa,M.getActiveUniform(a,b).name.length+1)}q[c>>2]=a.fa}else if(35722==b){if(!a.da)for(d=M.getProgramParameter(a,35721),b=0;b<d;++b)a.da=Math.max(a.da,M.getActiveAttrib(a,b).name.length+1);q[c>>2]=a.da}else if(35381==b){if(!a.ea)for(d=M.getProgramParameter(a,35382),b=0;b<d;++b)a.ea=Math.max(a.ea,M.getActiveUniformBlockName(a,b).length+1);q[c>>2]=a.ea}else q[c>>2]=M.getProgramParameter(a,b);else P||=1281},emscripten_glGetQueryObjecti64vEXT:ye,
emscripten_glGetQueryObjectivEXT:ze,emscripten_glGetQueryObjectui64vEXT:ye,emscripten_glGetQueryObjectuivEXT:ze,emscripten_glGetQueryivEXT:(a,b,c)=>{c?q[c>>2]=M.J.getQueryEXT(a,b):P||=1281},emscripten_glGetRenderbufferParameteriv:(a,b,c)=>{c?q[c>>2]=M.getRenderbufferParameter(a,b):P||=1281},emscripten_glGetShaderInfoLog:(a,b,c,d)=>{a=M.getShaderInfoLog(O[a]);null===a&&(a="(unknown error)");b=0<b&&d?E(a,l,d,b):0;c&&(q[c>>2]=b)},emscripten_glGetShaderPrecisionFormat:(a,b,c,d)=>{a=M.getShaderPrecisionFormat(a,
b);q[c>>2]=a.rangeMin;q[c+4>>2]=a.rangeMax;q[d>>2]=a.precision},emscripten_glGetShaderSource:(a,b,c,d)=>{if(a=M.getShaderSource(O[a]))b=0<b&&d?E(a,l,d,b):0,c&&(q[c>>2]=b)},emscripten_glGetShaderiv:(a,b,c)=>{c?35716==b?(a=M.getShaderInfoLog(O[a]),null===a&&(a="(unknown error)"),q[c>>2]=a?a.length+1:0):35720==b?(a=M.getShaderSource(O[a]),q[c>>2]=a?a.length+1:0):q[c>>2]=M.getShaderParameter(O[a],b):P||=1281},emscripten_glGetString:a=>{var b=vd[a];if(!b){switch(a){case 7939:b=Gd(Ae().join(" "));break;
case 7936:case 7937:case 37445:case 37446:(b=M.getParameter(a))||(P||=1280);b=b?Gd(b):0;break;case 7938:b=Gd(`OpenGL ES 2.0 (${M.getParameter(7938)})`);break;case 35724:b=M.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b=`OpenGL ES GLSL ES ${c[1]} (${b})`);b=Gd(b);break;default:P||=1280}vd[a]=b}return b},emscripten_glGetTexParameterfv:(a,b,c)=>{c?w[c>>2]=M.getTexParameter(a,b):P||=1281},emscripten_glGetTexParameteriv:(a,b,
c)=>{c?q[c>>2]=M.getTexParameter(a,b):P||=1281},emscripten_glGetUniformLocation:(a,b)=>{b=b?B(l,b):"";if(a=N[a]){De(a);var c=a.$,d=0,e=b,f=Be(b);0<f&&(d=parseInt(b.slice(f+1))>>>0,e=b.slice(0,f));if((e=a.Pa[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||M.getUniformLocation(a,b)))return d}else P||=1281;return-1},emscripten_glGetUniformfv:(a,b,c)=>{Ee(a,b,c,2)},emscripten_glGetUniformiv:(a,b,c)=>{Ee(a,b,c,0)},emscripten_glGetVertexAttribPointerv:(a,b,c)=>{c?q[c>>2]=M.getVertexAttribOffset(a,b):P||=1281},emscripten_glGetVertexAttribfv:(a,
b,c)=>{Fe(a,b,c,2)},emscripten_glGetVertexAttribiv:(a,b,c)=>{Fe(a,b,c,5)},emscripten_glHint:(a,b)=>M.hint(a,b),emscripten_glIsBuffer:a=>(a=od[a])?M.isBuffer(a):0,emscripten_glIsEnabled:a=>M.isEnabled(a),emscripten_glIsFramebuffer:a=>(a=pd[a])?M.isFramebuffer(a):0,emscripten_glIsProgram:a=>(a=N[a])?M.isProgram(a):0,emscripten_glIsQueryEXT:a=>(a=ud[a])?M.J.isQueryEXT(a):0,emscripten_glIsRenderbuffer:a=>(a=qd[a])?M.isRenderbuffer(a):0,emscripten_glIsShader:a=>(a=O[a])?M.isShader(a):0,emscripten_glIsTexture:a=>
(a=rd[a])?M.isTexture(a):0,emscripten_glIsVertexArrayOES:a=>(a=sd[a])?M.isVertexArray(a):0,emscripten_glLineWidth:a=>M.lineWidth(a),emscripten_glLinkProgram:a=>{a=N[a];M.linkProgram(a);a.$=0;a.Pa={}},emscripten_glPixelStorei:(a,b)=>{3317==a?wd=b:3314==a&&(xd=b);M.pixelStorei(a,b)},emscripten_glPolygonModeWEBGL:(a,b)=>{M.yb.polygonModeWEBGL(a,b)},emscripten_glPolygonOffset:(a,b)=>M.polygonOffset(a,b),emscripten_glPolygonOffsetClampEXT:(a,b,c)=>{M.eb.polygonOffsetClampEXT(a,b,c)},emscripten_glQueryCounterEXT:(a,
b)=>{M.J.queryCounterEXT(ud[a],b)},emscripten_glReadPixels:(a,b,c,d,e,f,g)=>{(g=Ge(f,e,c,d,g))?M.readPixels(a,b,c,d,e,f,g):P||=1280},emscripten_glReleaseShaderCompiler:()=>{},emscripten_glRenderbufferStorage:(a,b,c,d)=>M.renderbufferStorage(a,b,c,d),emscripten_glSampleCoverage:(a,b)=>{M.sampleCoverage(a,!!b)},emscripten_glScissor:(a,b,c,d)=>M.scissor(a,b,c,d),emscripten_glShaderBinary:()=>{P||=1280},emscripten_glShaderSource:(a,b,c,d)=>{for(var e="",f=0;f<b;++f){var g=(g=u[c+4*f>>2])?B(l,g,d?u[d+
4*f>>2]:void 0):"";e+=g}M.shaderSource(O[a],e)},emscripten_glStencilFunc:(a,b,c)=>M.stencilFunc(a,b,c),emscripten_glStencilFuncSeparate:(a,b,c,d)=>M.stencilFuncSeparate(a,b,c,d),emscripten_glStencilMask:a=>M.stencilMask(a),emscripten_glStencilMaskSeparate:(a,b)=>M.stencilMaskSeparate(a,b),emscripten_glStencilOp:(a,b,c)=>M.stencilOp(a,b,c),emscripten_glStencilOpSeparate:(a,b,c,d)=>M.stencilOpSeparate(a,b,c,d),emscripten_glTexImage2D:(a,b,c,d,e,f,g,m,n)=>{n=n?Ge(m,g,d,e,n):null;M.texImage2D(a,b,c,d,
e,f,g,m,n)},emscripten_glTexParameterf:(a,b,c)=>M.texParameterf(a,b,c),emscripten_glTexParameterfv:(a,b,c)=>{M.texParameterf(a,b,w[c>>2])},emscripten_glTexParameteri:(a,b,c)=>M.texParameteri(a,b,c),emscripten_glTexParameteriv:(a,b,c)=>{M.texParameteri(a,b,q[c>>2])},emscripten_glTexSubImage2D:(a,b,c,d,e,f,g,m,n)=>{n=n?Ge(m,g,e,f,n):null;M.texSubImage2D(a,b,c,d,e,f,g,m,n)},emscripten_glUniform1f:(a,b)=>{M.uniform1f(W(a),b)},emscripten_glUniform1fv:(a,b,c)=>{if(288>=b)for(var d=He[b],e=0;e<b;++e)d[e]=
w[c+4*e>>2];else d=w.subarray(c>>2,c+4*b>>2);M.uniform1fv(W(a),d)},emscripten_glUniform1i:(a,b)=>{M.uniform1i(W(a),b)},emscripten_glUniform1iv:(a,b,c)=>{if(288>=b)for(var d=Ie[b],e=0;e<b;++e)d[e]=q[c+4*e>>2];else d=q.subarray(c>>2,c+4*b>>2);M.uniform1iv(W(a),d)},emscripten_glUniform2f:(a,b,c)=>{M.uniform2f(W(a),b,c)},emscripten_glUniform2fv:(a,b,c)=>{if(144>=b){b*=2;for(var d=He[b],e=0;e<b;e+=2)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2]}else d=w.subarray(c>>2,c+8*b>>2);M.uniform2fv(W(a),d)},emscripten_glUniform2i:(a,
b,c)=>{M.uniform2i(W(a),b,c)},emscripten_glUniform2iv:(a,b,c)=>{if(144>=b){b*=2;for(var d=Ie[b],e=0;e<b;e+=2)d[e]=q[c+4*e>>2],d[e+1]=q[c+(4*e+4)>>2]}else d=q.subarray(c>>2,c+8*b>>2);M.uniform2iv(W(a),d)},emscripten_glUniform3f:(a,b,c,d)=>{M.uniform3f(W(a),b,c,d)},emscripten_glUniform3fv:(a,b,c)=>{if(96>=b){b*=3;for(var d=He[b],e=0;e<b;e+=3)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2],d[e+2]=w[c+(4*e+8)>>2]}else d=w.subarray(c>>2,c+12*b>>2);M.uniform3fv(W(a),d)},emscripten_glUniform3i:(a,b,c,d)=>{M.uniform3i(W(a),
b,c,d)},emscripten_glUniform3iv:(a,b,c)=>{if(96>=b){b*=3;for(var d=Ie[b],e=0;e<b;e+=3)d[e]=q[c+4*e>>2],d[e+1]=q[c+(4*e+4)>>2],d[e+2]=q[c+(4*e+8)>>2]}else d=q.subarray(c>>2,c+12*b>>2);M.uniform3iv(W(a),d)},emscripten_glUniform4f:(a,b,c,d,e)=>{M.uniform4f(W(a),b,c,d,e)},emscripten_glUniform4fv:(a,b,c)=>{if(72>=b){var d=He[4*b],e=w;c>>=2;b*=4;for(var f=0;f<b;f+=4){var g=c+f;d[f]=e[g];d[f+1]=e[g+1];d[f+2]=e[g+2];d[f+3]=e[g+3]}}else d=w.subarray(c>>2,c+16*b>>2);M.uniform4fv(W(a),d)},emscripten_glUniform4i:(a,
b,c,d,e)=>{M.uniform4i(W(a),b,c,d,e)},emscripten_glUniform4iv:(a,b,c)=>{if(72>=b){b*=4;for(var d=Ie[b],e=0;e<b;e+=4)d[e]=q[c+4*e>>2],d[e+1]=q[c+(4*e+4)>>2],d[e+2]=q[c+(4*e+8)>>2],d[e+3]=q[c+(4*e+12)>>2]}else d=q.subarray(c>>2,c+16*b>>2);M.uniform4iv(W(a),d)},emscripten_glUniformMatrix2fv:(a,b,c,d)=>{if(72>=b){b*=4;for(var e=He[b],f=0;f<b;f+=4)e[f]=w[d+4*f>>2],e[f+1]=w[d+(4*f+4)>>2],e[f+2]=w[d+(4*f+8)>>2],e[f+3]=w[d+(4*f+12)>>2]}else e=w.subarray(d>>2,d+16*b>>2);M.uniformMatrix2fv(W(a),!!c,e)},emscripten_glUniformMatrix3fv:(a,
b,c,d)=>{if(32>=b){b*=9;for(var e=He[b],f=0;f<b;f+=9)e[f]=w[d+4*f>>2],e[f+1]=w[d+(4*f+4)>>2],e[f+2]=w[d+(4*f+8)>>2],e[f+3]=w[d+(4*f+12)>>2],e[f+4]=w[d+(4*f+16)>>2],e[f+5]=w[d+(4*f+20)>>2],e[f+6]=w[d+(4*f+24)>>2],e[f+7]=w[d+(4*f+28)>>2],e[f+8]=w[d+(4*f+32)>>2]}else e=w.subarray(d>>2,d+36*b>>2);M.uniformMatrix3fv(W(a),!!c,e)},emscripten_glUniformMatrix4fv:(a,b,c,d)=>{if(18>=b){var e=He[16*b],f=w;d>>=2;b*=16;for(var g=0;g<b;g+=16){var m=d+g;e[g]=f[m];e[g+1]=f[m+1];e[g+2]=f[m+2];e[g+3]=f[m+3];e[g+4]=
f[m+4];e[g+5]=f[m+5];e[g+6]=f[m+6];e[g+7]=f[m+7];e[g+8]=f[m+8];e[g+9]=f[m+9];e[g+10]=f[m+10];e[g+11]=f[m+11];e[g+12]=f[m+12];e[g+13]=f[m+13];e[g+14]=f[m+14];e[g+15]=f[m+15]}}else e=w.subarray(d>>2,d+64*b>>2);M.uniformMatrix4fv(W(a),!!c,e)},emscripten_glUseProgram:a=>{a=N[a];M.useProgram(a);M.Wa=a},emscripten_glValidateProgram:a=>{M.validateProgram(N[a])},emscripten_glVertexAttrib1f:(a,b)=>M.vertexAttrib1f(a,b),emscripten_glVertexAttrib1fv:(a,b)=>{M.vertexAttrib1f(a,w[b>>2])},emscripten_glVertexAttrib2f:(a,
b,c)=>M.vertexAttrib2f(a,b,c),emscripten_glVertexAttrib2fv:(a,b)=>{M.vertexAttrib2f(a,w[b>>2],w[b+4>>2])},emscripten_glVertexAttrib3f:(a,b,c,d)=>M.vertexAttrib3f(a,b,c,d),emscripten_glVertexAttrib3fv:(a,b)=>{M.vertexAttrib3f(a,w[b>>2],w[b+4>>2],w[b+8>>2])},emscripten_glVertexAttrib4f:(a,b,c,d,e)=>M.vertexAttrib4f(a,b,c,d,e),emscripten_glVertexAttrib4fv:(a,b)=>{M.vertexAttrib4f(a,w[b>>2],w[b+4>>2],w[b+8>>2],w[b+12>>2])},emscripten_glVertexAttribDivisorANGLE:(a,b)=>{M.vertexAttribDivisor(a,b)},emscripten_glVertexAttribPointer:(a,
b,c,d,e,f)=>{M.vertexAttribPointer(a,b,c,!!d,e,f)},emscripten_glViewport:(a,b,c,d)=>M.viewport(a,b,c,d),emscripten_has_asyncify:()=>1,emscripten_request_fullscreen_strategy:(a,b,c)=>Je(a,{sa:q[c>>2],ma:q[c+4>>2],fb:q[c+8>>2],$a:b,ba:q[c+12>>2],xa:q[c+16>>2]}),emscripten_request_pointerlock:(a,b)=>{a=Q(a);return a?a.requestPointerLock?Nd()?se(a):b?(Ld(se,2,[a]),1):-2:-1:-4},emscripten_resize_heap:()=>{za("OOM")},emscripten_sample_gamepad_data:Ke,emscripten_set_beforeunload_callback_on_thread:(a,b,
c)=>"undefined"==typeof onbeforeunload?-1:1!==c?-5:Le(a,b),emscripten_set_blur_callback_on_thread:(a,b,c,d)=>Me(a,b,c,d,12,"blur"),emscripten_set_canvas_element_size:me,emscripten_set_element_css_size:(a,b,c)=>{a=Q(a);if(!a)return-4;a.style.width=b+"px";a.style.height=c+"px";return 0},emscripten_set_focus_callback_on_thread:(a,b,c,d)=>Me(a,b,c,d,13,"focus"),emscripten_set_fullscreenchange_callback_on_thread:(a,b,c,d)=>{if(!Ud())return-1;a=Q(a);if(!a)return-4;Ne(a,b,c,d,"webkitfullscreenchange");return Ne(a,
b,c,d,"fullscreenchange")},emscripten_set_gamepadconnected_callback_on_thread:(a,b,c)=>Ke()?-1:Oe(a,b,c,26,"gamepadconnected"),emscripten_set_gamepaddisconnected_callback_on_thread:(a,b,c)=>Ke()?-1:Oe(a,b,c,27,"gamepaddisconnected"),emscripten_set_keydown_callback_on_thread:(a,b,c,d)=>Pe(a,b,c,d,2,"keydown"),emscripten_set_keypress_callback_on_thread:(a,b,c,d)=>Pe(a,b,c,d,1,"keypress"),emscripten_set_keyup_callback_on_thread:(a,b,c,d)=>Pe(a,b,c,d,3,"keyup"),emscripten_set_mousedown_callback_on_thread:(a,
b,c,d)=>Re(a,b,c,d,5,"mousedown"),emscripten_set_mouseenter_callback_on_thread:(a,b,c,d)=>Re(a,b,c,d,33,"mouseenter"),emscripten_set_mouseleave_callback_on_thread:(a,b,c,d)=>Re(a,b,c,d,34,"mouseleave"),emscripten_set_mousemove_callback_on_thread:(a,b,c,d)=>Re(a,b,c,d,8,"mousemove"),emscripten_set_mouseup_callback_on_thread:(a,b,c,d)=>Re(a,b,c,d,6,"mouseup"),emscripten_set_pointerlockchange_callback_on_thread:(a,b,c,d)=>{if(!document||!document.body||!(document.body.requestPointerLock||document.body.o||
document.body.qb||document.body.oa))return-1;a=Q(a);if(!a)return-4;Se(a,b,c,d,"mozpointerlockchange");Se(a,b,c,d,"webkitpointerlockchange");Se(a,b,c,d,"mspointerlockchange");return Se(a,b,c,d,"pointerlockchange")},emscripten_set_resize_callback_on_thread:(a,b,c,d)=>Te(a,b,c,d),emscripten_set_touchcancel_callback_on_thread:(a,b,c,d)=>Ue(a,b,c,d,25,"touchcancel"),emscripten_set_touchend_callback_on_thread:(a,b,c,d)=>Ue(a,b,c,d,23,"touchend"),emscripten_set_touchmove_callback_on_thread:(a,b,c,d)=>Ue(a,
b,c,d,24,"touchmove"),emscripten_set_touchstart_callback_on_thread:(a,b,c,d)=>Ue(a,b,c,d,22,"touchstart"),emscripten_set_visibilitychange_callback_on_thread:(a,b,c)=>Ve(a,b,c),emscripten_set_wheel_callback_on_thread:(a,b,c,d)=>(a=Q(a))?"undefined"!=typeof a.onwheel?We(a,b,c,d):-1:-4,emscripten_set_window_title:a=>document.title=a?B(l,a):"",emscripten_sleep:a=>of(b=>Mc(b,a)),environ_get:(a,b)=>{var c=0;Ze().forEach((d,e)=>{var f=b+c;e=u[a+4*e>>2]=f;for(f=0;f<d.length;++f)k[e++]=d.charCodeAt(f);k[e]=
0;c+=d.length+1});return 0},environ_sizes_get:(a,b)=>{var c=Ze();u[a>>2]=c.length;var d=0;c.forEach(e=>d+=e.length+1);u[b>>2]=d;return 0},exit:oc,fd_close:function(a){try{var b=Lb(a);Zb(b);return 0}catch(c){if("undefined"==typeof J||"ErrnoError"!==c.name)throw c;return c.s}},fd_read:function(a,b,c,d){try{a:{var e=Lb(a);a=b;for(var f,g=b=0;g<c;g++){var m=u[a>>2],n=u[a+4>>2];a+=8;var p=e,t=f,v=k;if(0>n||0>t)throw new F(28);if(null===p.N)throw new F(8);if(1===(p.flags&2097155))throw new F(8);if(I(p.node.mode))throw new F(31);
if(!p.i.read)throw new F(28);var r="undefined"!=typeof t;if(!r)t=p.position;else if(!p.seekable)throw new F(70);var A=p.i.read(p,v,m,n,t);r||(p.position+=A);var D=A;if(0>D){var H=-1;break a}b+=D;if(D<n)break;"undefined"!=typeof f&&(f+=D)}H=b}u[d>>2]=H;return 0}catch(T){if("undefined"==typeof J||"ErrnoError"!==T.name)throw T;return T.s}},fd_seek:function(a,b,c,d,e){b=c+2097152>>>0<4194305-!!b?(b>>>0)+4294967296*c:NaN;try{if(isNaN(b))return 61;var f=Lb(a);$b(f,b,d);z=[f.position>>>0,(y=f.position,1<=
+Math.abs(y)?0<y?+Math.floor(y/4294967296)>>>0:~~+Math.ceil((y-+(~~y>>>0))/4294967296)>>>0:0)];q[e>>2]=z[0];q[e+4>>2]=z[1];f.P&&0===b&&0===d&&(f.P=null);return 0}catch(g){if("undefined"==typeof J||"ErrnoError"!==g.name)throw g;return g.s}},fd_write:function(a,b,c,d){try{a:{var e=Lb(a);a=b;for(var f,g=b=0;g<c;g++){var m=u[a>>2],n=u[a+4>>2];a+=8;var p=ac(e,k,m,n,f);if(0>p){var t=-1;break a}b+=p;if(p<n)break;"undefined"!=typeof f&&(f+=p)}t=b}u[d>>2]=t;return 0}catch(v){if("undefined"==typeof J||"ErrnoError"!==
v.name)throw v;return v.s}},invoke_ii:xf,invoke_iii:yf,invoke_iiii:zf,invoke_iiiii:Af,invoke_iiiiii:Bf,invoke_iiiiiiiiii:Cf,invoke_jiji:Df,invoke_vi:Ef,invoke_vii:Ff,invoke_viii:Gf,proc_exit:nc},X=function(){function a(c){X=c.exports;X=bf();ja=X.memory;c=ja.buffer;h.HEAP8=k=new Int8Array(c);h.HEAP16=ma=new Int16Array(c);h.HEAPU8=l=new Uint8Array(c);h.HEAPU16=na=new Uint16Array(c);h.HEAP32=q=new Int32Array(c);h.HEAPU32=u=new Uint32Array(c);h.HEAPF32=w=new Float32Array(c);h.HEAPF64=x=new Float64Array(c);
pa.unshift(X.__wasm_call_ctors);ya("wasm-instantiate");return X}var b={env:Hf,wasi_snapshot_preview1:Hf};xa("wasm-instantiate");if(h.instantiateWasm)try{return h.instantiateWasm(b,a)}catch(c){return aa(`Module.instantiateWasm callback failed with error: ${c}`),!1}Ba||=Aa("index.wasm")?"index.wasm":h.locateFile?h.locateFile("index.wasm",ea):ea+"index.wasm";Fa(b,function(c){a(c.instance)});return{}}(),C=a=>(C=X.malloc)(a),sf=a=>(sf=X.free)(a),If=h._main=(a,b)=>(If=h._main=X.__main_argc_argv)(a,b),wf=
a=>(wf=X.fileno)(a),fb=(a,b)=>(fb=X.emscripten_builtin_memalign)(a,b),vf=(a,b)=>(vf=X._emscripten_timeout)(a,b),Jf=(a,b)=>(Jf=X.setThrew)(a,b),U=a=>(U=X._emscripten_stack_restore)(a),je=a=>(je=X._emscripten_stack_alloc)(a),R=()=>(R=X.emscripten_stack_get_current)(),dynCall_vi=h.dynCall_vi=(a,b)=>(dynCall_vi=h.dynCall_vi=X.dynCall_vi)(a,b),dynCall_vii=h.dynCall_vii=(a,b,c)=>(dynCall_vii=h.dynCall_vii=X.dynCall_vii)(a,b,c),dynCall_v=h.dynCall_v=a=>(dynCall_v=h.dynCall_v=X.dynCall_v)(a),Kf=h.dynCall_ii=
(a,b)=>(Kf=h.dynCall_ii=X.dynCall_ii)(a,b),Lf=h.dynCall_iiiii=(a,b,c,d,e)=>(Lf=h.dynCall_iiiii=X.dynCall_iiiii)(a,b,c,d,e),Mf=h.dynCall_jiji=(a,b,c,d,e)=>(Mf=h.dynCall_jiji=X.dynCall_jiji)(a,b,c,d,e);h.dynCall_ji=(a,b)=>(h.dynCall_ji=X.dynCall_ji)(a,b);var Nf=h.dynCall_viii=(a,b,c,d)=>(Nf=h.dynCall_viii=X.dynCall_viii)(a,b,c,d),dynCall_iii=h.dynCall_iii=(a,b,c)=>(dynCall_iii=h.dynCall_iii=X.dynCall_iii)(a,b,c);h.dynCall_viiii=(a,b,c,d,e)=>(h.dynCall_viiii=X.dynCall_viiii)(a,b,c,d,e);
var V=h.dynCall_iiii=(a,b,c,d)=>(V=h.dynCall_iiii=X.dynCall_iiii)(a,b,c,d),Of=h.dynCall_iiiiii=(a,b,c,d,e,f)=>(Of=h.dynCall_iiiiii=X.dynCall_iiiiii)(a,b,c,d,e,f);h.dynCall_iiiiiiii=(a,b,c,d,e,f,g,m)=>(h.dynCall_iiiiiiii=X.dynCall_iiiiiiii)(a,b,c,d,e,f,g,m);var Pf=h.dynCall_iiiiiiiiii=(a,b,c,d,e,f,g,m,n,p)=>(Pf=h.dynCall_iiiiiiiiii=X.dynCall_iiiiiiiiii)(a,b,c,d,e,f,g,m,n,p);
h.dynCall_iiiiiiiiiiiiiiff=(a,b,c,d,e,f,g,m,n,p,t,v,r,A,D,H)=>(h.dynCall_iiiiiiiiiiiiiiff=X.dynCall_iiiiiiiiiiiiiiff)(a,b,c,d,e,f,g,m,n,p,t,v,r,A,D,H);h.dynCall_viiiii=(a,b,c,d,e,f)=>(h.dynCall_viiiii=X.dynCall_viiiii)(a,b,c,d,e,f);h.dynCall_viiiiiiiii=(a,b,c,d,e,f,g,m,n,p)=>(h.dynCall_viiiiiiiii=X.dynCall_viiiiiiiii)(a,b,c,d,e,f,g,m,n,p);h.dynCall_iiiiiiiii=(a,b,c,d,e,f,g,m,n)=>(h.dynCall_iiiiiiiii=X.dynCall_iiiiiiiii)(a,b,c,d,e,f,g,m,n);
h.dynCall_iiiiiii=(a,b,c,d,e,f,g)=>(h.dynCall_iiiiiii=X.dynCall_iiiiiii)(a,b,c,d,e,f,g);h.dynCall_viiiiiiii=(a,b,c,d,e,f,g,m,n)=>(h.dynCall_viiiiiiii=X.dynCall_viiiiiiii)(a,b,c,d,e,f,g,m,n);h.dynCall_i=a=>(h.dynCall_i=X.dynCall_i)(a);h.dynCall_viiiiiii=(a,b,c,d,e,f,g,m)=>(h.dynCall_viiiiiii=X.dynCall_viiiiiii)(a,b,c,d,e,f,g,m);h.dynCall_viiiiiiiiiii=(a,b,c,d,e,f,g,m,n,p,t,v)=>(h.dynCall_viiiiiiiiiii=X.dynCall_viiiiiiiiiii)(a,b,c,d,e,f,g,m,n,p,t,v);
h.dynCall_iiiiiidiiff=(a,b,c,d,e,f,g,m,n,p,t)=>(h.dynCall_iiiiiidiiff=X.dynCall_iiiiiidiiff)(a,b,c,d,e,f,g,m,n,p,t);h.dynCall_viiiiii=(a,b,c,d,e,f,g)=>(h.dynCall_viiiiii=X.dynCall_viiiiii)(a,b,c,d,e,f,g);h.dynCall_vffff=(a,b,c,d,e)=>(h.dynCall_vffff=X.dynCall_vffff)(a,b,c,d,e);h.dynCall_vf=(a,b)=>(h.dynCall_vf=X.dynCall_vf)(a,b);h.dynCall_vff=(a,b,c)=>(h.dynCall_vff=X.dynCall_vff)(a,b,c);h.dynCall_vfi=(a,b,c)=>(h.dynCall_vfi=X.dynCall_vfi)(a,b,c);
h.dynCall_viif=(a,b,c,d)=>(h.dynCall_viif=X.dynCall_viif)(a,b,c,d);h.dynCall_vif=(a,b,c)=>(h.dynCall_vif=X.dynCall_vif)(a,b,c);h.dynCall_viff=(a,b,c,d)=>(h.dynCall_viff=X.dynCall_viff)(a,b,c,d);h.dynCall_vifff=(a,b,c,d,e)=>(h.dynCall_vifff=X.dynCall_vifff)(a,b,c,d,e);h.dynCall_viffff=(a,b,c,d,e,f)=>(h.dynCall_viffff=X.dynCall_viffff)(a,b,c,d,e,f);h.dynCall_vfff=(a,b,c,d)=>(h.dynCall_vfff=X.dynCall_vfff)(a,b,c,d);
h.dynCall_iidiiii=(a,b,c,d,e,f,g)=>(h.dynCall_iidiiii=X.dynCall_iidiiii)(a,b,c,d,e,f,g);h.dynCall_iid=(a,b,c)=>(h.dynCall_iid=X.dynCall_iid)(a,b,c);h.dynCall_di=(a,b)=>(h.dynCall_di=X.dynCall_di)(a,b);h.dynCall_jij=(a,b,c,d)=>(h.dynCall_jij=X.dynCall_jij)(a,b,c,d);h.dynCall_iij=(a,b,c,d)=>(h.dynCall_iij=X.dynCall_iij)(a,b,c,d);var qf=a=>(qf=X.asyncify_start_unwind)(a),ff=()=>(ff=X.asyncify_stop_unwind)(),pf=a=>(pf=X.asyncify_start_rewind)(a),rf=()=>(rf=X.asyncify_stop_rewind)();
function Af(a,b,c,d,e){var f=R();try{return Lf(a,b,c,d,e)}catch(g){U(f);if(g!==g+0)throw g;Jf(1,0)}}function xf(a,b){var c=R();try{return Kf(a,b)}catch(d){U(c);if(d!==d+0)throw d;Jf(1,0)}}function zf(a,b,c,d){var e=R();try{return V(a,b,c,d)}catch(f){U(e);if(f!==f+0)throw f;Jf(1,0)}}function Ef(a,b){var c=R();try{dynCall_vi(a,b)}catch(d){U(c);if(d!==d+0)throw d;Jf(1,0)}}function Ff(a,b,c){var d=R();try{dynCall_vii(a,b,c)}catch(e){U(d);if(e!==e+0)throw e;Jf(1,0)}}
function Gf(a,b,c,d){var e=R();try{Nf(a,b,c,d)}catch(f){U(e);if(f!==f+0)throw f;Jf(1,0)}}function Cf(a,b,c,d,e,f,g,m,n,p){var t=R();try{return Pf(a,b,c,d,e,f,g,m,n,p)}catch(v){U(t);if(v!==v+0)throw v;Jf(1,0)}}function Bf(a,b,c,d,e,f){var g=R();try{return Of(a,b,c,d,e,f)}catch(m){U(g);if(m!==m+0)throw m;Jf(1,0)}}function yf(a,b,c){var d=R();try{return dynCall_iii(a,b,c)}catch(e){U(d);if(e!==e+0)throw e;Jf(1,0)}}
function Df(a,b,c,d,e){var f=R();try{return Mf(a,b,c,d,e)}catch(g){U(f);if(g!==g+0)throw g;Jf(1,0)}}h.addRunDependency=xa;h.removeRunDependency=ya;h.FS_createPreloadedFile=sb;h.FS_unlink=a=>Tb(a);h.FS_createPath=bc;h.FS_createDevice=dc;h.FS_createDataFile=(a,b,c,d,e,f)=>{rb(a,b,c,d,e,f)};h.FS_createLazyFile=fc;h.allocate=Ga;var Qf;wa=function Rf(){Qf||Sf();Qf||(wa=Rf)};
function Tf(a=[]){var b=If;a.unshift(da);var c=a.length,d=je(4*(c+1)),e=d;a.forEach(g=>{u[e>>2]=ke(g);e+=4});u[e>>2]=0;try{var f=b(c,d);oc(f,!0)}catch(g){lc(g)}}
function Sf(){var a=ca;function b(){if(!Qf&&(Qf=!0,h.calledRun=!0,!ka)){if(!h.noFSInit&&!zb){var c,d;zb=!0;e??=h.stdin;c??=h.stdout;d??=h.stderr;e?dc("/dev","stdin",e):Sb("/dev/tty","/dev/stdin");c?dc("/dev","stdout",null,c):Sb("/dev/tty","/dev/stdout");d?dc("/dev","stderr",null,d):Sb("/dev/tty1","/dev/stderr");Xb("/dev/stdin",0);Xb("/dev/stdout",1);Xb("/dev/stderr",1)}Ab=!1;Oa(pa);Oa(qa);h.onRuntimeInitialized?.();Uf&&Tf(a);if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;){var e=
h.postRun.shift();ra.unshift(e)}Oa(ra)}}if(!(0<ta)){if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)sa();Oa(oa);0<ta||(h.setStatus?(h.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>h.setStatus(""),1);b()},1)):b())}}if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.pop()();var Uf=!0;h.noInitialRun&&(Uf=!1);Sf();
